lua/menu.lua, lua/norns.lua, lua/startup.lua
version.txt just contains a string ie 180531
=> menu checks ~/version.txt for current version

lua/menu.lua
mute monitor by default
mute inputs to aux by default
set output -> aux to -9db
reorder params, put output -> aux above inputs
=> fix audio defaults

lua/script.lua
grid leds don't actually blank otherwise...
/cc @tehn @catfact
=> refresh grid on clear

readme-setup.md
=> update repo locations

lua/script.lua
reset `gridkey` on script clear.
/cc @tehn @catfact
=> reset gridkey on clear

lua/grid.lua, lua/midi.lua
i think this is needed for https://github.com/monome/norns/blob/master/lua/grid.lua#L27 and https://github.com/monome/norns/blob/master/lua/midi.lua#L22 to work?
=> enable device unplug callbacks

lua/menu.lua, sc/ugens/FaustZitaRevLight/FaustZitaRevLight.cpp, sc/ugens/FaustZitaRevLight/FaustZitaRevLight.dsp
some broken reverb params fixed in this commit.
note, the cpp stuff is hacked without faust code generation.
=> fix aux reverb lf x/in delay/low and high decay times

lua/script.lua
i believe it's better to this kind of cleanup in core instead of per script: https://github.com/monome/dust/blob/master/scripts/tehn/mlr.lua#L828-L830
https://github.com/monome/dust/blob/master/scripts/jah/hello_ack.lua#L367-L369
hence this pr
=> automatic cleanup of midi dev callbacks

lua/script.lua
clear all connected grids, not only `g`.
=> more extensive grid cleanup

update.sh_template
re: https://github.com/monome/norns/issues/471#issuecomment-409802053
=> update.sh template

lua/menu.lua, lua/paramset.lua, lua/update.lua, readme.md
- fix accel (enc2 should be on for MIX mode) fixes #376 
- shorten menu press time fixes #482 
- aux naming fixes #488 
- don't copy old updates fixes #458 
- also fix MIX fader display now that we have -inf (bonus)
- added documentation link to README
=> various minor fixes

lua/menu.lua, lua/state.lua
=> On startup, only resume last script if we shutdown cleanly

sc/ugens/SoftCutHead/SoftCutHead.cpp, sc/ugens/SoftCutHead/SoftCutHead.sc, sc/ugens/SoftCutHead/SoftCutHeadLogic.cpp
make more stuff happen at audio rate. 
reorder ugen inputs to make AR and KR inputs easier to follow. this is a breaking change, better now than later
this is WIP, will try to add (slightly) better write resampling. the current version is so bad and wrong that it actually skips write samples, making recording at rate>1 very glitchy (and never erasing)
=> Softcut improvements

lua/audio.lua, lua/encoders.lua, lua/fileselect.lua, lua/menu.lua, lua/metro.lua, lua/params/control.lua, lua/params/file.lua, lua/params/number.lua, lua/params/option.lua, lua/params/separator.lua, lua/paramset.lua, lua/script.lua, lua/startup.lua, lua/state.lua, lua/textentry.lua, lua/update.lua, lua/util.lua, lua/wifi.lua
also fixed my vim config, sorry for the mess
also: minor error message display fix in menu.lua
=> lua whitespace cleanup

sc/ugens/SoftCutHead/SoftCutHead.cpp, sc/ugens/SoftCutHead/SoftCutHeadLogic.cpp
=> softcut: restore peek4, whitespace cleanup

sc/core/Crone.sc
=> fix tape play

readme-setup.md
Update the APT repo to the correct syntax, DRY up some docs, make link clickable
=> Documentation updates

lua/tabutil.lua
I've been finding these functions useful for saving data within scripts. They let you save simple tables to disk and load them back. I didn't write them, they're from http://lua-users.org/wiki/SaveTableToFile and licensed under "the same terms as lua itself".
Will need ldoc running on it.
Not totally sure if this is the right place for these or if there are plans for other preset management APIs, happy to put these into my own lib instead if so.
=> Added functions to tabutil to save and load tables from disk

sc/core/Crone.sc, sc/core/CroneDefs.sc
=> enable input level

lua/midi.lua, matron/src/device/device.c
small commit to remove misleading debug print output (complete with differing index bases)
=> Deconfusify device dbg

matron/src/hardware/battery.c
=> fix battery current draw digits

lua/grid.lua, lua/midi.lua
fixes https://github.com/monome/norns/issues/561
=> fix midi/grid recon/discon

lua/menu.lua, lua/script.lua, lua/startup.lua, matron/src/hardware/screen.c, matron/src/hardware/screen.h, matron/src/weaver.c
=> cairo save/restore

lua/menu.lua, lua/params/control.lua, lua/params/file.lua, lua/params/trigger.lua, lua/paramset.lua
New param type: `trigger`
Creates an item in the param list that will fire its `action` when key3 is pressed. Is not saved.
Also fixed typos at the top of `file` and `control`.
=> Add simple trigger param type

lua/menu.lua
issues systemctl messages for crone.
auto-disables crone when turning on wifi in router mode.
LOG removed from SYSTEM menu.
this is a short-term fix.
=> audio reset within menu

lua/paramset.lua
fixes https://github.com/monome/norns/issues/569
=> paramset add table helper

lua/engine.lua, lua/menu.lua, lua/paramset.lua, lua/poll.lua, lua/script.lua
fixes https://github.com/monome/norns/issues/577
=> script loading fix

lua/script.lua
fixes https://github.com/monome/norns/issues/579
=> set defaults to screen attributes on cleanup

lua/menu.lua, lua/script.lua
somehow broke this after fixing it the first time.
also fixed engine-less script loading
=> Screen state fix

lua/menu.lua
=> restore menu.init function, used by fileselect

.travis.yml
wip: playing w/ travis.
see #590
=> [wip] initial travis config

readme.md
=> add api doc link

matron/src/oracle.c, matron/src/oracle.h, matron/src/weaver.c, sc/core/Crone.sc, sc/core/CroneEngine.sc
allow lua to explicitly stop and deallocate the current engine.
also minor tweak that may help with CPU spikes when switching engines.
=> Free engine

lua/script.lua, sc/core/Crone.sc
properly resets engine on cleanup
@markwheeler shouldn't need to dummy-load testsine now
=> free engine on cleanup

lua/menu.lua, lua/norns.lua, lua/script.lua, matron/src/event_types.h, matron/src/events.c, matron/src/hardware/stat.c, matron/src/hardware/stat.h, matron/src/main.c, matron/src/weaver.c, matron/src/weaver.h, matron/wscript, sc/core/Crone.sc
instead of calling `os.execute` from lua (which clogs up the scheduler) now all the stat functions (temp, cpu, disk free) are in c, refreshed on a thread.
=> stat functions

lua/mix.lua, sc/core/CroneEffects.sc
revert to lighter-cpu reverb. adds only 9% now.
=> reverb light

lua/mix.lua, sc/core/CroneEffects.sc
=> restore normal reverb, fixes level mapping

matron/src/hardware/i2c.c, matron/src/hardware/i2c.h, matron/src/weaver.c
gain stages not present in production units.
=> i2c cpu bugfix

lua/menu.lua
fixes https://github.com/monome/norns/issues/624
=> match encoder behaviors in mix menu

sc/install.sh
...  in case they got nuked somehow
(@okyeron is this what you meant?)
=> make parent directories for sc install locations

lua/script.lua
arc works fine without this, but looks like the change won't hurt.
=> reconnect arc in script.init()

sc/core/Crone.sc
crude tape level sc hack
also: lagged amp
=> tape level

lua/menu.lua
fixes #673
@catfact is this all that is needed?  I grepped .wav and that was the only use I could find
=> update filename of tape recordings to aiff extension

lua/core/config.lua, lua/core/menu.lua, lua/core/paramset.lua
- fix midi learn
- fix system.pset
- fix pmap read/write
=> various param fixes

wifi.sh
Aware that wifi.sh will very likely be replaced, still this might come in handy, who knows?
=> better error messages for wifi.sh gw fails

lua/core/audio.lua, lua/core/menu.lua, lua/core/mix.lua, lua/core/softcut.lua, lua/core/startup.lua
add softcut and ext levels to MIX/LEVELS menu UI
move params around
add softcut input levels (they live in the audio context)
formatting
=> lua softcut add

crone/src/Tape.h
fix a pretty stupid bug where disk worker threads in crone-tape weren't updating their "needs data / data ready" flags. so they were basically busy-waiting on ringbuffer contents, instead of sleeping on their condition variables.
(this took an embarassing amount of work to find, but at least now i have a demangling `perf` on rasbpi!)
i also changed read/write logic to use the largest possible chunk size instead of single frames, which should also speed things up in theory. (the footprint of the actual disk work is vanishingly small though.) 
hopefully this addresses the usage reported in issue #697, though i have not yet addressed the hard click on stop/start. (next PR.)
=> Crone tape optimize

matron/src/args.c
same change as https://github.com/monome/norns/pull/710, but for dev (fixes a trivial merge conflict)
=> fix gcc new -Wstringop-truncation warning (dev branch)

lua/core/arc.lua, lua/core/grid.lua, lua/core/metro.lua, lua/core/midi.lua, lua/core/norns.lua, lua/core/osc.lua, lua/core/params/control.lua, lua/core/paramset.lua, lua/core/screen.lua, lua/core/softcut.lua, lua/user/lib/intonation.lua, lua/user/lib/tabutil.lua, lua/user/lib/ui.lua, lua/user/lib/util.lua
fixes, additions and cleanup of midi.lua and grid.lua
=> grid and midi ldoc cleanup

sc/core/Crone.sc, stop.sh
shell commands threw a jack could not connect error
kill scsynth instead of supernova in `stop.sh`
=> remove obsolete supernova refs, use scsynth

lua/core/menu.lua, lua/core/script.lua, lua/user/lib/fileselect.lua, lua/user/lib/listselect.lua, matron/src/weaver.c
was 0-indexed.
sorry! will mess up some user scripts.
=> change font_face function to 1-indexed

lua/core/arc.lua, lua/core/audio.lua, lua/core/engine.lua, lua/core/menu.lua, lua/core/metro.lua, lua/core/midi.lua, lua/core/osc.lua, lua/core/params/control.lua, lua/core/poll.lua, lua/core/screen.lua, lua/core/script.lua, lua/core/state.lua
second round of ldoc formatting cleanup
=> ldoc formatting cleanup

lua/core/config.lua, lua/core/menu.lua, lua/core/paramset.lua, lua/core/script.lua, lua/core/state.lua
apologies for the late change. trying to keep things clean ahead of public beta.
scripts/projects now get stored in dust/scripts as is the case now with the master branch. otherwise the audio and data folders just get lost.
confirmed working with maiden.
=> dust script dir

lua/core/menu.lua
=> fix tape extension

lua/lib/gridbuf.lua
=> re-add gridbuf

lua/core/softcut.lua, matron/src/oracle.c, matron/src/oracle.h, matron/src/weaver.c
adds oracle/matron/lua glue for
https://github.com/monome/norns/pull/759
=> glue for #759

lua/core/audio.lua
Am I on the right track with these doc additions to `audio.lua`?
=> ldoc updates - audio

lua/lib/musicutil.lua
- Added a simple function to generate chords with inversions.
- Added a function to return chords that fit a given root note and key. Took kind of a brute force approach to this - generating a table offline by testing all the chords against all the scales. Would love to hear if there's a smarter way or if it's even that useful?!
- `tparams` for ldocs
=> Chords in musicutil

doc/reference.md
=> enc doc typo

lua/lib/listselect.lua
fixes https://github.com/monome/norns/issues/743
=> empty list notification for listdisplay

lua/core/audio.lua, lua/core/menu.lua, lua/core/mix.lua
first pass on the lua and user facing bits.
TODO matron glue
=> rename "ext" to "eng"/"engine"

doc/crone/softcut-routing.tex
added latex source for softcut routing diagram
rendered:
[softcut-routing.pdf](https://github.com/monome/norns/files/3076831/softcut-routing.pdf)
=> softcut routing doc

lua/lib/ui.lua
Small tweak that allows more pages to be shown
=> UI lib update to pages

matron/src/hardware/screen.c
=> fix for display_png file not found crash

lua/core/clock.lua
started on ldoc for clocks based on info at #712
might need additional clarification on data types for each function.
=> first pass at clock.lua ldocs

lua/core/encoders.lua, lua/core/menu.lua, lua/core/screen.lua
fixes https://github.com/monome/norns/issues/314
=> screensaver fix, ping on keys/encs

crone/src/softcut/SoftCutVoice.cpp, crone/src/softcut/Svf.cpp
un-bork pre-filter frequency modulation.
=> fix softcut pre-filter mod

crone/src/softcut/SoftCutHead.cpp
spotted by @catfact, tested on hardware. fixes https://github.com/monome/norns/issues/868
=> fix samplerate

crone/src/Commands.h, crone/src/OscInterface.cpp, crone/src/SoftCutClient.cpp, crone/src/softcut/SoftCut.h, crone/src/softcut/SoftCutVoice.cpp, crone/src/softcut/SoftCutVoice.h, lua/core/softcut.lua
fixes https://github.com/monome/norns/issues/876
tested on hardware
=> add level and pan slew, rename old level slew to recpre slew

crone/src/Bus.h, crone/src/SoftCutClient.cpp
fixes https://github.com/monome/norns/issues/817
tested on hardware
=> flip and  rescale pan

lua/core/crow.lua
a crack at a simple crow reset
fixes #893 
/cc @tehn @trentgill
=> crow reset

lua/core/paramset.lua
=> fix print for unnamed params

.travis.yml
=> move api doc location

lua/core/menu.lua
fixes a leak.
💧 
see: #425
/cc @tehn
=> remove leaked `line` 

lua/lib/pattern_time.lua
i'm not sure about this api or implementation but i'd like to be able to do something like this so consider it food for thought.
the idea is for scripts to be able to nudge tempo of recorded patterns.  (for example, speed up or slow down earthsea.)
/cc @tehn
=> time factoring for patterns

lua/core/softcut.lua
not sure if this was tripping anyone up but it sure looks wrong 🤔 
/cc @catfact @tehn
=> fix arg mismatch

lua/lib/elca.lua
=> fix BOUND accesses

lua/core/script.lua, lua/core/wifi.lua, lua/lib/beatclock.lua, lua/lib/formatters.lua
a few locals, leaked.
💧💧💧 
see: #559 
/cc @tehn @catfact @markwheeler
=> cleanup leaked globals

lua/core/clock.lua
=> localize leaked globals

lua/core/clock.lua
This fixes the behavior observed in #907.
=> Give clock coroutines unique IDs

lua/lib/musicutil.lua
Tiny change that I think makes sense but also realized doesn't look any different on device 😁
=> musicutil uses proper sharp symbol

lua/core/crow.lua
similar to grid, allow user scripts to handle when a crow device is added or removed.
=> allow user scripts to redefine crow.add and crow.remove

lua/core/engine.lua
=> error msg for missing engine

crone/src/SoftCutClient.cpp
fixees https://github.com/monome/norns/issues/964
spotted by @catfact 
tested/works
=> crone fix buffer load length

crone/src/SoftCutClient.cpp
=> Revert "crone fix buffer load length"

lua/lib/fileselect.lua, lua/lib/util.lua
In response to https://github.com/monome/norns/issues/637
=> Display audio file length in fileselect and trim filename to screen

lua/lib/util.lua
Minor addition to string trim util. Should have added this in the last PR sorry!
=> Cleaner string trimming

lua/core/menu.lua, lua/core/menu/home.lua, lua/core/script.lua
hold K1 when executing SELECT and the script (and environment) will be halted/cleared.
=> script clear hotkey

lua/core/softcut.lua
redo after forced reset of upstream
=> fixes to softcut.defaults(), and lots of docstrings

readme-setup.md
The instructions didn't work for me.  The ncurses libraries are missing and the softcut submodule needs to be initialized.
=> add missing dependencies and git submodules

crone/src/BufDiskWorker.cpp, crone/src/MixerClient.cpp
output meters are presently pre-fader; i'm sure this is a mistake (on my part), 
can't believe nobody said anything!
here is the fix if we want it
this also pulls in #1022
=> Output meters postfader

lua/core/config.lua, lua/core/menu/tape.lua, lua/core/state.lua
fixes #1026 
- `dust/audio/tape/index.txt` contains ascending tape index number
- textentry dialog upon tape rec arm
=> tape index, naming

lua/core/audio.lua, lua/core/state.lua
=> save mix state between scripts and boots

lua/core/menu/params.lua, lua/core/paramset.lua, lua/core/startup.lua
fixes #1044 
- makes return state for `params:visible` correct
- rebuilds menu on entry (fixes display of param menu with show/hide changes)
- add `inf = math.huge` globally (fixes mix saving problem, plus it makes sense)
=> fix hide/show, add inf global

lua/core/audio.lua, lua/core/state.lua
fixed bug, don't save rev/comp state
=> do not save param mix levels

lua/core/paramset.lua
ie
```
params:hide(1)
params:show("LEVELS")
```
@dndrks
=> allow ids in addition to indexes for show/hide

lua/core/menu/params.lua
=> script reset param menu position

lua/core/params/option.lua
=> clamp val for option params

maiden-repl/wscript
=> maiden-repl: Fix typo in pedantic compile argument

matron/src/clocks/clock_midi.c
=> clock start/stop sync for midi

lua/core/clock.lua
allows for some cleaner param code
=> select source clock by number also

lua/core/clock.lua, matron/src/clock.h, matron/src/clocks/clock_crow.c, matron/src/clocks/clock_crow.h, matron/src/device/device_crow.c, matron/src/main.c, matron/wscript
this works, though i'm not sure it's super useful due to the jitter. perhaps some smoothing will help.
=> crow clock initial support

lua/core/clock.lua, lua/core/script.lua
add clock menu at script start
=> clock menu

lua/core/clock.lua, matron/src/clock.c, matron/src/device/device_crow.c
sorry for the small PRs
crow clock input is fixed to input 1.
increased clock threads to 100 @artfwo
=> increase threads, change crow input port to 1

matron/src/clocks/clock_midi.c
=> average intervals for incoming midi clock events

matron/src/clocks/clock_crow.c
=> clock crow input smoothing

lua/core/clock.lua
added crow clear in clock menu, in case input isn't working.
=> clock menu crow clear

readme-setup.md, sc/core/Crone.sc, sc/wscript
Whilst removing the supernova ugen compilation I noticed we still had some other references to supernova in some places, so I removed those as well. LMK if that's OK.
=> Remove supernova remainders

lua/core/crow.lua, lua/core/script.lua
if clock source set to crow:
- successfully connects on script startup if crow already connected
- sets up clock if crow connected while script running
thanks for spotting this @simonvanderveldt
=> reconnect crow clock

lua/core/menu/params.lua
=> pset save cancel fix

lua/core/clock.lua
allows additional control over how and when clock coroutines
execute through explicit use of suspend and resume along side
existing sleep and sync scheduling
- automatically cancels clocks when their coroutine completes
- print warning when a canceled clock is resumed
=> add clock.create, clock.suspend

lua/lib/formatters.lua
Small update that makes viewing long times nicer.
=> Updated secs formatter to displays mins and hours

lua/lib/pattern_time.lua
adds overdub mode to pattern time
huge thanks to @dndrks for testing and debugging
=> pattern time overdub

lua/lib/filters.lua
fix an initial spike in value with the lua onepole smoothing filter.
=> small fix to filters.smoother

lua/lib/container/deque.lua, lua/lib/container/deque_test.lua, lua/lib/container/observable.lua, lua/lib/container/observable_test.lua, lua/lib/container/watchtable.lua, lua/lib/container/weaktable.lua, lua/lib/test/luaunit.lua
these container type objects are used in various places within sky but are independent/generic and are structured like traditional lua module/objects
adds:
- `Deque`
- `Observable` (value)
- `WeakTable` (a table configured with weakly held keys)
- `WatchTable` (notifies observers when a key changes)
this PR also adds a copy of `luaunit` under `norns/lua/lib/test/`
=> some container objects

lua/extn/sky/core/object.lua, lua/extn/sky/prelude.lua, lua/extn/sky/unstable.lua, lua/extn/sky/unstable/core/page.lua, lua/extn/sky/unstable/device/es.lua, lua/extn/sky/unstable/device/linn.lua, lua/extn/sky/unstable/engine/polysub.lua, lua/extn/sky/unstable/io/arc.lua, lua/extn/sky/unstable/io/grid.lua, lua/extn/sky/unstable/io/norns.lua, lua/extn/sky/v1.lua, lua/extn/sky/v1/core/event.lua, lua/extn/sky/v1/core/process.lua, lua/extn/sky/v1/device/arp.lua, lua/extn/sky/v1/device/behavior.lua, lua/extn/sky/v1/device/clock_div.lua, lua/extn/sky/v1/device/filter.lua, lua/extn/sky/v1/device/make_note.lua, lua/extn/sky/v1/device/switcher.lua, lua/extn/sky/v1/device/transpose.lua, lua/extn/sky/v1/device/utility.lua, lua/extn/sky/v1/device/virtual.lua
this is (very) light on documentation but long in ambition. my intention is to:
- work up some combination of reference documentation
- start a [studies](https://github.com/ngwese/sky-studies) type series
- stabilize the norns, arc, then grid abstractions (input end is okay, output/visualization bits are still rough)
=> sky - the beginning

lua/core/crow.lua, lua/core/crow/ii_actions.lua, lua/core/crow/ii_events.lua
Updated bindings for new crow features in v2.0
- NEW input modes
- NEW output scales
- CHANGE i2c event callback signature
- NEW additional i2c device support
=> Crow v2 support

lua/core/crow.lua
Tiny patch to fix serialized transmission of tables (for input 'scale' and 'window' and output 'scale')
All v2.0 features tested and working well!
=> Crow v2- fix stringification of tables

lua/lib/util.lua
=> cleanup util.time() param name, comment

lua/lib/filters.lua
corrects a typo noted by @catfact in #1155
=> fix median bufsize calculation

lua/lib/ui.lua
@markwheeler What do you think about this feature?  If there is something you want slightly different just let me know I can work on it.
=> give UI.Slider direction

crone/src/BufDiskWorker.cpp, crone/src/BufDiskWorker.h
=> crone BufDiskWorker: replace sleep with condvar

lua/lib/er.lua
=> ER module: correctly handle request for empty table; add shift param

lua/lib/container/deque.lua, lua/lib/container/deque_test.lua
adds some additional methods to the `Deque` container type.
=> deque: add peek, peek_back, and find methods

maiden-repl/src/ui.c
=> allow for capital Z to be typed

lua/core/config.lua, lua/core/menu/reset.lua, lua/core/menu/select.lua
Related to #1200 I would like to add a separate selection at the top right now, but this will at least add an asterisk next to any script selected as a favorite.
=> First pass at adding 'favorites'.

crone/src/SoftcutClient.cpp, crone/src/SoftcutClient.h
alternate fix for #1209 
this is completely untested! (it compiles.)
=> Clamp softcut parameters

lua/lib/musicutil.lua
=> revert sharps

lua/core/menu/home.lua, lua/core/script.lua
quick fix to make sure the engine is never double-cleared
fixes #1215 better
=> no double free for CLEAR

lua/core/encoders.lua, lua/core/menu.lua, lua/core/script.lua
fixes  #1236
increases default playmode encoder sensitivity to 2 (from 1) for all encoders
=> default enc sensitivity

edge.sh
convenience script for users to test pre-release updates to `main`
via ssh/screen:
```
norns/edge.sh
systemctl restart norns*
```
maiden:
```
os.execute("/home/we/norns/edge.sh")
;restart
```
=> add script to pull main and recompile

lua/core/screen.lua
implementation examples: https://github.com/northern-information/athenaeum/blob/main/text_rotate.lua
=> text rotation

lua/core/menu/update.lua
make shield update less confusing (presently it's ambiguous what do to when it says "shutdown")
=> shield update shutdown message

lua/core/menu.lua, lua/core/menu/home.lua
=> fix script clear

lua/core/norns.lua
use `;install` in maiden instead (which can also be accessed via http post and cli)
=> remove norns.fetch()

lua/lib/lattice.lua
based on #1280 !
example usage: https://github.com/tyleretters/lattice
```lua
lattice = require("lattice")
-- basic lattice usage
my_lattice = lattice:new()
-- make some tracks
track_a = my_lattice:new_track(1/2, function() print("half notes") end)
track_b = my_lattice:new_track(1/4, function() print("quarter notes") end)
-- optionally add a track that is disabled
track_c = my_lattice:new_track(1/8, function() print("eighth notes") end, false)
-- start the lattice
my_lattice:start()
-- user definable callbacks
my_lattice.downbeat = function(transport)
print("downbeat", transport)
end
-- another one, but in in 5/4 and 128 ppqn
my_other_lattice = lattice:new(5, 128)
-- global lattice controls
my_lattice:stop()
my_lattice:start()
my_lattice:toggle()
my_lattice:destroy() …
```
=> add lattice

lua/core/arc.lua, lua/core/keyboard.lua, lua/core/menu/preview.lua, lua/core/menu/select.lua
=> stray nonlocal tabs

lua/core/audio.lua
from https://llllllll.co/t/norns-update-210114/40494/19
@tehn , i think this is everything...
=> hotfix norns.state.mix typos

lua/core/state.lua
=> set sane defaults for audio params

lua/core/crow.lua, lua/core/crow/ii_actions.lua, lua/core/crow/ii_events.lua
* W/2.0 `ii` commands as `wtape`, `wdel` and `wsyn`
* crow `ii` commands as `crow`
* Disting EX `ii` commands as `disting`
* adds `crow.loadscript(file, is_persistent)` for uploading a local lua script to crow. optional `is_persistent` flag will save to crow's internal flash so it will run without norns attached. Searches in a `crow/` subfolder for local storage, and falls back to `dust/code/`
* fixes situation where clocksource = 'crow' could fail if crow was running a script with a custom input.stream event
=> Crow update 2.1.2

lua/core/crow.lua
Fixes `_norns.crow.event` parser for the situation where crow sends a bunch of text that gets split over 2 separate usb packets. Previously any line over the packet limit would cause a norns event error, then the end of the string would be printed to console.
Now we maintain a buffer for any lines that are not terminated by line-endings.
=> FIX parser for multiple lines across multiple packets

lua/core/params/control.lua
adds a get_range method to control type parameters.
=> adds get_range() to control params

matron/src/clock.c, matron/src/clock.h, matron/src/clocks/clock_crow.c, matron/src/clocks/clock_crow.h, matron/src/clocks/clock_internal.c, matron/src/clocks/clock_internal.h, matron/src/clocks/clock_link.c, matron/src/clocks/clock_link.h, matron/src/clocks/clock_midi.c, matron/src/clocks/clock_midi.h, matron/src/clocks/clock_scheduler.c, matron/src/clocks/clock_scheduler.h, matron/src/main.c, matron/src/weaver.c, matron/wscript
=> merge new clock to main

matron/src/clocks/clock_internal.c
=> clock_internal: use absolute tick times for clock_nanosleep

matron/src/clocks/clock_link.c, matron/src/clocks/clock_scheduler.c
=> fix start/stop sync in link clock source

matron/src/device/device_crow.c, matron/src/device/device_monitor.c, matron/src/device/device_monome.c
basically just check the product string before sending on the tty device to the crow ^^identity check, to avoid sending unexpected bytes to a random tty device
also re-tabbed. sorry for the mess, this file was a crazy mix.
=> do not assume unmatched tty is crow

matron/src/device/device_monome.c
sorry i didn't test the earlier merge, and now for the github noise
this fixes it
=> arc quad fix

lua/core/crow.lua, lua/core/crow/quote.lua
i'd failed to push my most recent commit on the namespace branch, so this commit contains the fix to get input stream & ii events working
CC @tehn @dndrks
=> hotfix crow namespace bug 

lua/lib/util.lua
adds a `util` function which returns a file's size in megabytes:
```lua
> util.file_size(_path.code.."awake/awake.lua")
0.013152
> util.file_size(_path.audio.."tape/0000.wav")
71.710508
```
- if provided filepath isn't found:
```lua
> util.file_size(_path.audio.."tape/blahblah.wav")
no file found at /home/we/dust/audio/tape/blahblah.wav
<ok>
```
- if no path is provided:
```lua
> util.file_size()
util.file_size requires a path
<ok>
```
=> add util.file_size

lua/core/clock.lua
=> hotfix reduce clock pulsewidth to 10ms

lua/core/clock.lua
enforce 50% duty cycle for clock out
=> crow clock out fix

lua/lib/sequins.lua
this is just a straight port from https://github.com/monome/crow/blob/34ce1e455f01fdef65a0d37aa97163b4cd14a115/lua/sequins.lua
@trentgill said it would be just a copy paste job and was right!
=> port sequins to norns

matron/src/hardware/screen.c
This error message would have helped me a bit while exploring the code.
=> Provide more information on screen open error.

matron/src/hardware/stat.c
When running in a docker container `vcgencmd` isn't going to be available and we fail with the following message:
```
we@e821707a6a8c:~/norns$ ./matron.sh 
attempting to bind socket at url ws://*:5555
*** WARNING *** The program 'matron' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=matron>
sh: 1: vcgencmd: not found
child killed (signal 11)
```
What happens is the command returns 127 and writes `vcgencmd: not found` to stderr. There is no other output so `fgets` doesn't read anything so the temp is not updated.
When making this PR I thought this was related to the `child killed (signal 11)` crash, but that is unrelated.
=> Graceful handling for vcgencmd not installed.

lua/core/menu/tape.lua
=> Fix double increment introduced by #1420

lua/core/menu/devices.lua
=> Fix empty HID list introduced by #1408, uniformise select behavior

lua/core/script.lua
as mentioned in #1430 the system handles script cleanup differently depending on whether the `script.clear` function was called or the `script.load` function as call and the running script needs to be cleaned up.
this change ensures the `script_post_cleanup` hook is run in all circumstances and ensures that script cleanup behavior is consistent regardless of whether it is triggered directly or indirectly. 
update: this does not address the ux problems which result when the maiden stop button is used.
cc/ @p3r7
=> unify cleanup behavior between script clear and load

matron/src/args.c, matron/src/args.h, matron/src/oracle.c, matron/src/osc.c
Parameterize a magic number, and put it in the boot log for extra visibility.
=> Configurable OSC remote port.

lua/lib/tabutil.lua
This filter creates a new table based on the passing the existing table values through a condition - similar to JS Array.filter method
=> Add select_values method to tabutil lib

sc/norns-config.sc
because it doesn't exist anymore?
=> remove ugen path in sc config

watcher/src/main.c
fixes error (warning) and gives some minor feedback
=> watcher pw reset msg

lua/core/menu/update.lua, lua/core/norns.lua, update/update.sh, watcher/src/main.c
fix various systemd service calls to match v3 norns-image config
=> v3 service fixes

lua/lib/lattice.lua
this gives lattice a more desired behavior to run its patterns in order of creation (i.e. in order of its pattern id).
this is really useful if you want to separate musical things into different patterns, i.e. one pattern for chord progression changes and one pattern for playing notes of the chord - in such case you would always want the chord progression change to occur before notes play. this can be easily accomplished by pulsing through patterns in order of their id (by default patterns are added with incrementing ids).
to emulate this, consider this lua test example:
```lua
-- lattice test
local lattice=require("lattice")
local my_lattice = lattice:new()
local shared_value=0
first_pattern=my_lattice:new_pattern{
action = function(t) shared_value=shared_value+100 end, …
```
=> lattice: patterns pulse in order based on id

lua/core/config.lua, lua/engine/polyperc.lua, lua/engine/polysub.lua, lua/extn/sky/unstable/engine/polysub.lua, sc/engines/Engine_PolyPerc.sc, sc/engines/Engine_PolySub.sc, sc/engines/Engine_SimplePassThru.sc, sc/engines/Engine_TestSine.sc
deprecating `we` repo
including these few basic engines as standard
=> add engines, lua/engine folder

crone/wscript, wscript
alt to #1532
`./waf --release`
=> release build flags

edge.sh
not sure how often this script is used but figured it should probably default to release builds
=> ensure edge.sh does release builds

norns/wscript, wscript
- fix/rename flag to enable gprof profiling
- add flag to enable debugging/syms
- fix duplicate/conflicting c++ standard flags
- add help strings to some configure flags
=> various build improvements

readme-setup.md
=> Update readme-setup.md to libnng-dev

.gitmodules, matron/src/clocks/clock_link.c, matron/wscript, third-party/wscript
ableton link has official C bindings now, this PR updates link clock to use them.
=> use abl_link C API for link clock

lua/lib/lfospec.lua
This suggestion does one of the things I reccommended:
* Uses lattice instead of a raw clock, so the LFOs can easily share a clock
* Allows the user to specify the ppqn per-LFO. Values that divide 96 evenly are going to be better, because they won't leave residual phase in the lattice, but other values are okay — they just won't bang quite _exactly_ on the dot every time.
* I hope I have not been misusing the `hook` library, but it was useful.
=> Use lattice for LFOs, so they share clocks, and allow setting ppqn

lua/lib/lfo.lua
okay, actually done now @tehn -- what a ride, very sorry for the trouble!!
=> rest of the lfo hotfix

lua/lib/lattice.lua
whoops, should probably document one of the main new features of v2
=> fix: document sprocket ordering

lua/lib/lfo.lua
- updated use of `pattern` from lattice v1.2.1 to `sprocket` from lattice v2 (cosmetic, avoids warning message in REPL)
- following @Dewb 's [example in his nc03 `gimbal` script](https://github.com/monome-community/nc03-ds/blob/954d0b6300ca80bbf5527016a20c1aa0fbe789df/gimbal.lua#L639-L654), added guardrails so that changes to an lfo's period do not interrupt its phase. this avoids discontinuities in the outgoing data as the speed of the lfo changes.
=> lfo lib: lattice v2 + change period without interrupting phase

lua/lib/util.lua
fixes https://github.com/monome/norns/issues/1576
=> Notate that wrap accepts integers; reimplement to be constant-time

matron/src/device/device_midi.c
blind fix attempt for dropped sysex bytes. (we don't actually want to start a new message on the stop byte.)
attn @okyeron
=> [untested] attempt fix for dropped sysex bytes

crone/src/OscInterface.cpp
this is a blind fix attempt for issue #1652
=> fix argument indices for buffer_clear_region_channel

update/update.sh
=> disable hciuart in update

lua/lib/fileselect.lua
hi! i added a naïve debounce of one second to fileselect tape playback. happy to tweak further if desired!
=> fix: debounce tape preview in fileselect (closes #1628)

lua/core/crow.lua, lua/lib/textentry.lua, update/update.sh
=> string.char to utf8.char

lua/core/menu/select.lua
optimization via https://llllllll.co/t/norns-installed-scripts-not-displaying-in-norns-script-list/59433/23
=> optimize file listing

matron/src/device/device_monitor.c
This is a tiny change but since I was investigating monome/norns-image#101, I found those changes helpful. Should be uncontroversial to merge.
I mostly cared about including name and node information but once I was on it, I also made the other messages more consistent with each other.
=> Make dev_monitor messages more consistent and informative

lua/lib/reflection.lua
here are some proposed changes that address timing errors when using `queued_rec` to record pattern loops.
the problem: when using `queued_rec` recording is triggered by `reflection:watch(event)`, so the recording and step count happens _after_ the first event is recorded, which results in subsequent events being recorded earlier that the actual distance between the first step. also, as `reflection:watch(event)` calls `self:set_rec(1, self.queued_rec.duration)` without a `beat_sync` arg the difference between first and subsequent steps is greater with larger quantization values. In addition, when looping, the playback starts late, because the duration counter starts late with `begin_playback()`.
this [test script](https://gist.github.com/sonocircuit/86be456e4bc82dc1425566bfae02e63d) fires …
=> reflection: queued_rec timing fix

lua/lib/reflection.lua
omg, i know, so much `reflection` traffic lately!! but the library is _so_ rad and i thought it'd be nice to include a helper for saving/loading pattern data.
usage:
- save: `my_pattern:save(norns.state.data.."pattern.txt")`
- load: `my_pattern:load(norns.state.data.."pattern.txt")`
@ryleelyman + @sonocircuit : please lemme know if there are any q's or blindspots!
=> reflection: add pattern save + load

lua/core/encoders.lua, lua/core/menu.lua, lua/core/menu/mix.lua, lua/core/norns.lua, matron/src/hardware/i2c.c, matron/src/hardware/i2c.h, matron/src/weaver.c
includes a fix the the encoder module's sensitivity feature
=> i2c adc hotfix

lua/lib/fileselect.lua
=> Revert "fix: more aggressively debounce tape playback"

lua/core/menu/home.lua, lua/core/norns.lua, lua/core/script.lua
=> script clear frees engine

matron/src/device/device_monitor.c
clarified some debug messages as well
=> detect cdc arc

matron/src/device/device_monitor.c
Still working with my 2015 grid. Should fix the issue in this [llllllll thread](https://llllllll.co/t/grid-stopped-working-after-update/71505/1).
=> fix detection of 2012 grids
