lua/audio.lua
lua/menu.lua
lua/norns.lua
lua/startup.lua
matron/src/event_types.h
matron/src/events.c
matron/src/hello.c
matron/src/hello.h
matron/src/main.c
matron/src/oracle.c
matron/src/oracle.h
matron/src/weaver.c
matron/src/weaver.h

implemented changes described in https://github.com/monome/norns/issues/381
this makes `audio.restart()` lua method more functional, as a first step for editing SC classes. (`audio.restart()` should now re-trigger the main startup sequence, including resuming last script and sending audio I/O and effect parameters.)
it also means that if SC fails to boot, you get a timeout message but can continue to use the menu to turn on wifi.

Refactor crone startup

---

lua/menu.lua
lua/norns.lua
lua/paramset.lua
lua/script.lua
lua/startup.lua
lua/update.lua

- SYSTEM > UPDATE now simply primes an update. grabs file from USB disk, extracts it to ~/update
- on boot, ~/update is checked for any updates and then executes them if available. shut down upon completion
- BREAKING CHANGE: parameter sets moved to subfolders ie tehn/awake.pset
- hold KEY1 in PARAMETER menu to bring up load/save.
- ENC3 scrolls slot (default is 0)
- then use KEY2/KEY3 to save/load to slot positions.
- "slot" files saved with -nn extension ie awake-02.pset
- save/load status/fade shown, load dimmed for nonexistent files
- NEEDED: dust updates for default .pset files and loading within `init` of any script doing `params:read()`
- when navigating into ie `/tehn` and then backing out, the select position will resume from `/tehn`

menu: update method, multiple paramset slots

---

lua/script.lua

fixes: #358
(there's another `pcall` in `cleanup()` that could maybe get similar treatment, but since there's a `norns.try` right after maybe that's intended?)
/cc @tehn @catfact

report errors in script init

---

lua/norns.lua

the error from `pcall` in `norns.try` is not super useful when the error is in a nested call.
notice in particular, that it's not clear what line _in user code_ caused the error.
`xpcall` w/ a `dbug.traceback()` hander gives us a bunch more context.
/cc @tehn @catfact

migrate `try` to use an `xpcall` for more context on errors

---

lua/util.lua

Three commits in here:
- The first adds some comments for documentation for the undocumented methods in `util.lua`. I wasn't sure how the docs were generated so this is just the lua file.
- The second commit is a suggestion to add a method to `util.lua` for generating note name strings from MIDI note numbers. Let me know if this should go elsewhere.
- The third requires a little more explaining...
It seemed that the existing `util.expexp()` method was returning invalid values outside of range. This method was pulled directly from [this snippet](https://github.com/supercollider/supercollider/blob/cca12ff02a774a9ea212e8883551d3565bb24a6f/lang/LangSource/MiscInlineMath.h#L49) of SC and matches. However, looking at [this other snippet](https://github.com/supercollider/supercollider/blob/a51dad …

Util.lua additions and fixes

---

crone.sh
matron.sh
ws-wrapper/src/main.c

- move WS_SOCKET arg before exec [+args]
- treat all args after WS_SOCKET as child args
- fix out of bounds indexing into parent argv
- switch execv to execvp allowing exe to be found via PATH
NOTE: merging this requires merging the companion changes to the systemd units in `norns-image` (forthcoming PR).

ws-wrapper: exec child with correct argv

---

lua/menu.lua
lua/screen.lua
matron/src/hardware/screen.c
matron/src/hardware/screen.h
matron/src/hello.c
matron/src/weaver.c

fixes https://github.com/monome/norns/issues/412
fixes https://github.com/monome/norns/issues/410
fixes https://github.com/monome/norns/issues/395
also adds `screen.pixel(x,y)` (lua)

various screen fixes

---

lua/menu.lua
lua/textentry.lua

I'm one of those unlucky people whose home wifi network has a space both in the network SSID and the password. This PR contains the following changes, which allow me to connect:
* Adds a space character to `textentry.lua`. The space is rendered as a space; a good future enhancement might be to display some kind of dim _ character to make selecting and entering it clearer.
* Quotes the network SSID and password arguments when calling `wifi.sh select`.

Support spaces in Wi-Fi network SSIDs and passwords

---

lua/script.lua

follow-up from https://github.com/monome/dust/pull/131#discussion_r198365764.
to be clear, i have no midi devices handy but based on a related fix for `gridkey` (https://github.com/monome/norns/commit/2e6762b409db0186156772137d1462734fc9ccd6) i'm thinking this is probably right.  would be awesome if someone could confirm. 👍 
/cc @artfwo @tehn

reset midi callbacks on script clear

---

lua/menu.lua
lua/midi.lua
lua/paramset.lua

- allows mapping from any midi device's cc inputs.
- there is no differentiation between devices (TODO, with the general device manager)
- "pmap" files are read/write for persistence, per script, like a "pset" file
- if a cc is assigned to multiple params it will only affect one, the first indexed
- only CONTROL type params mappable (because they have `set_raw` for scaling)
howto:
- with midi controller connected
- load script (ie earthsea)
- go to PARAMETERS
- hold KEY1 (alt menu)
- ENC2 scroll down to `midi-cc mapping`, use ENC3 to enable
- you're now back on the param list, but showing cc assignment numbers.
- use ENC3 to change cc number _or_
- push KEY3 to toggle LEARN, whereupon you can tweak the midi cc to auto-assign

PARAMETER menu midi cc mapping

---

lua/menu.lua

This is a revised version of #467 that only disables acceleration for encoder 2.
Tested navigating through very long and very short menus alike, and it seems good.
Issue #376

Disable acceleration within menu

---

lua/menu.lua

To go from specific (script) to generic/system
I've not mode the SELECT and PARAMETERS code blocks around, do we want to do that so their order is the same as it's in the menu?

menu.lua change order of main menu items

---

lua/grid.lua

Looks like this arg got mis-named and wasn't being used in the function.

fix to grid.connect() arg

---

lua/paramset.lua

small addition to make it possible to specify action directly in `params:add`

ParamSet:add now uses table argument

---

lua/grid.lua
lua/midi.lua

since USB device removal is flaky (due to the last update to make midi and grids coexist, while we debug the linux usb system) the functionality for same-named usb device causes more problems and does not work correctly.
temporarily commented out until the linux usb is fixed.

remove functionality for duplicate device names

---

lua/script.lua

another script environment management experiment. 
sets up a metatable for script state allowing scripts to shadow but not clobber state in `_G` [1]. script state is zeroed on script runs so scripts don't accumulate surprising state.
unlike #426 which introduces a fresh env that scripts are loaded into, this continues to use `_G` and so the repl "just works".
(tested on grid apps; not midi.)
see also: #258 
/cc @catfact @tehn @ngwese 
---
[1] qualification: "shallow" state or something; writing into (pre)existing tables in `_G` will stick.

[experiment] script state metatable

---

lua/midi.lua

Added support for 'channel pressure' to midi.lua
Also suggesting to rename polyphonic 'aftertouch' -> 'key pressure' for clarity.
This ref seems to use this as preferred naming but I can revert if need be: https://www.midi.org/specifications-old/item/table-1-summary-of-midi-message
Note: I don't have a device which supports polyphonic key pressure to double check it but it should be fine :)

MIDI channel pressure

---

lua/grid.lua
lua/midi.lua

Found a few odd things working with grids and midi today, here are some fixes:
- Grids now work after `reconnect`. Looked like some things had been copied across from midi that needed updating(?)
- Moved the grid cols/rows code to the `update_devices` method and tidied a bit. They weren't updating correctly on hot swap before, this seems to fix.
- Additionally, I've exposed grid cols/rows so you can access them like this:
`my_grid = grid.connect(1)`
`print(my_grid.cols())`
- MIDI `attached` function just seemed to be missing `self.` when reconnecting.
These are two classes I'm not very familiar with so please give these changes a good looking over 😄

Fixes to grid reconnect, cols and rows, midi attached status.

---

lua/menu.lua

enable midi map and learn for scripts that use taper parameters (glut, easygrain, channel changer)

enable midi map and learn for taper

---

matron/src/hardware/battery.c

this fixes a compiler warning, since we read 8 bytes into the buffer from `/sys/class/power_supply/bq27441-0/current_now`

fix battery read buffer size

---

lua/metro.lua

I ran into an issue where I had allocated too many metros.  I wasn't sure what the statement "nothing available" meant, so I had to go look through the code.  This pr just updates what is printed to the REPL in this case to something a bit less ambiguous.

add info to print statement on maxing out metro.alloc

---

lua/menu.lua
lua/osc.lua
lua/paramset.lua

fixes #501 
incoming numeric osc param values should be within the specific parameter range (i.e. -80, 20). file and option params require string argument value.

map incoming osc to params

---

sc/core/Crone.sc

tape synthdef looked funky, like it was multiplying the output by an envelope specifiction.
also doesn't really need varispeed

Crone tape

---

lua/params/number.lua
lua/paramset.lua

This adds formatters to numbers, just as controls can have.
Not sure if this goes against design plans but it's useful for displaying MIDI note names in the params menu.

Add formatters to numbers

---

matron/src/event_types.h
matron/src/hardware/gpio.c

minor broken-windows things:
- posting `key` events was setting data fields as if they were `enc` events
- comments describing event structure sizes were all rotted.

use the right accessor union for key events, and fix comments

---

lua/grid.lua
matron/src/device/device_monome.c
matron/src/device/device_monome.h
matron/src/weaver.c

Adds function to rotate grid.
```
local g = grid.connect()
g.rotation(1) -- 0,1,2,3 are options for 0,90,180,270
```
Needs menu.lua work to make it a configurable setting in menu.

grid rotation

---

lua/script.lua

This ensures that any tables that implement a finalizer with the metatable method `.__gc(self)` will have their finalizers run before the next script loads.
It doesn't look like any scripts currently in `dust` are using finalizers, but this feature is coming in handy while prototyping some `beatclock` changes.

Call collectgarbage() when clearing script

---

lua/encoders.lua
lua/menu.lua
lua/metro.lua
lua/mix.lua
lua/state.lua
lua/util.lua
matron/src/metro.c
matron/src/oracle.c
matron/src/oracle.h
matron/src/weaver.c
sc/core/Crone.sc

overhaul of the primary menu system.
ENC1 now changes pages:
`levels` - `tape` - `HOME` - `params`
KEY2 to toggle active level editing with ENC2/ENC3 (highlight shows edit position)
KEY2 to toggle between PLAY AND REC
PLAY: KEY3 to select file. KEY3 again to play. KEY3 again to stop. autostop implemented at EOF
REC: KEY3 to arm. KEY3 again to start. KEY3 again to stop. files names by incrementing counter, saved in `dust/data/system.lua`
KEY2 to toggle minimal vs. stats view
same as before. KEY2 unused, but can be allocated to other functionality with forthcoming params revision
---
- tape output has a level (thanks @antonhornquist )
- encoder sensitivity rewritten (massively improved)
- util function s_to_hms (sec to hour:minute:second string format)

menu revision

---

lua/midi.lua

Fix to midi.lua for some midi instruments that send a note-on, velocity zero instead of note-off
per https://github.com/monome/norns/issues/646

midi note-off variation

---

lua/params/control.lua
lua/paramset.lua
lua/util.lua

Cleans up leaked globals:
* `p`
* `us`
* `s`
* `clamped_value`
See: #559.
/cc @catfact @artfwo @tehn

localize leaked globals

---

lua/startup.lua
lua/tabutil.lua

a crack at guarding tables generally and `engine` in particular.
* adds `readonly` API to `tabutil`
* wraps `engine` import in `startup` with a read-only proxy
closes: #663; fixes: #656 
/cc @tehn @catfact @artfwo

engine table protection

---

lua/midi.lua

Update to previous midi fixes.
Adds 
- midi send helper functions for start, stop, continue and clock
- `Midi.to_msg(data)` conversions for those types as well.
I did not add `to_data` conversions for these as they have no data so just the send helper function can be used.

Add start/stop/continue/clock helpers

---

lua/core/arc.lua

otherwise a bunch of nil errors are thrown (trying to execute a nil function) when the functions are initially undefined. of course the user script should redefine them, but this will help avoid confusion.
we could alternatively define these functions as `function() end` instead of `nil`. there's a helper function `norns.none` that is a nil function, but this should really be renamed and moved (so probably not used)
similar fixes possibly needed with grid/midi/etc?

add delta/key function nil check

---

lua/core/menu.lua
lua/core/paramset.lua
lua/core/script.lua
lua/core/state.lua
lua/user/lib/util.lua

- auto-create `dust/data/(script)` when needed
- auto-copy "preset data" `dust/script/data` to "local data" `dust/data/`
basically the new system distinguishes "project" data from "local" data. think of it as default presets. so a project (git repo usually) can include a bunch of default pset data that then gets copied to the local data folder on first run.
future: restore default pset function? (or just copy stuff with sftp)

dust data folders

---

lua/core/arc.lua
lua/core/grid.lua
lua/core/hid.lua
lua/core/hid_events.lua
lua/core/menu.lua
lua/core/midi.lua
lua/core/norns.lua
lua/core/script.lua
lua/core/state.lua
lua/core/vport.lua
lua/user/lib/gridbuf.lua
matron/src/device/device.c
matron/src/device/device_hid.c
matron/src/device/device_hid.h
matron/src/device/device_list.c
matron/src/weaver.c

input/output API changes:
- use colon syntax when sending data to peripheral devices (`g:led`, not `g.led`)
- use dot syntax for now when assigning callbacks (`g.key = function(x, y, s) ... end`)
- `grid.event` has been renamed to `grid.key`
hid usage example:
```
local point_x = 0
local point_y = 0
h = hid.connect(2)
hid.event = function(type, code, value)
if type == hid.types.EV_REL then
if code == hid.codes.REL_X then
point_x = point_x + value
elseif code == hid.codes.REL_Y then
point_y = point_y + value
end
print(point_x, point_y)
end
end
```

vport api overhaul

---

lua/core/arc.lua
lua/core/grid.lua
lua/core/hid.lua
lua/core/midi.lua
lua/core/script.lua

reconnect shouldn't be used with vports and its functionality is redundant for scripts that want to use devices directly, hence we can safely remove it.

remove reconnect stub from input devices

---

crone/CMakeLists.txt
crone/readme-macos.md

re-do of #707. allows hacking on `crone` if you're stuck with macOS.

Crone osx picked

---

lua/paramset.lua

Tiny improvement to how trigger params are handled - skips calling bang() on triggers when bang() is called on all params. Think this makes more sense.

Don't fire triggers when calling bang() on ParamSet

---

matron/src/args.c

gcc 8.2.1 throws a warning here, which is blocking the build on my machine...
I guess the reason for this is as follows: max string length in N bytes (as per strncpy) is N-1 because the terminating '0' char at the end doesn't count as part of the string.  This snippet shows the problem:
https://gist.github.com/ranch-verdin/f8d26395a7d5cf89cc60f8cbd4262aa1
The warning actually only shows when you use -O3, which looks to me like a gcc bug!  (minimal test case exhibits a bug with or without -O3)

fix gcc new -Wstringop-truncation warning

---

lua/core/screen.lua
matron/src/hardware/screen.c
matron/src/hardware/screen.h
matron/src/weaver.c

Cairo screen function to load png files to the display.
lua syntax: `screen.display_png(filename, x, y)`
@artfwo suggested this should probably be two functions (one for load and one for display). However I won't have time to get back to this for a few days so I thought I'd submit it now for basic functionality.

Add display png function

---

lua/core/arc.lua

i'm assuming this should be `arc:led`, not `arc:let`

rename arc led function

---

lua/core/script.lua

- norns.state.path ends in '/' when script loaded
(fixes pmap load failure)
_this is half of the change needed to make the play button in maiden work again_

script load accepts paths relative to data_dir

---

matron/src/hardware/gpio.c

unfortunately discovered that the encoders might develop problems over time due to assembly method.
symptom: pulses are noisy, so the encoder overlay might translate them a bursts of values which may also flip direction.
this PR adds debouncing. it checks for faster-than-possible rotation ticks and for reversals of direction at physically-impossible rates. magic numbers determined by trial and error on hardware.
i welcome any suggestions on improving this algo.

encoder soft fix

---

lua/core/menu.lua

change `cleanup()` to `pcall(cleanup)` to fix failure to sleep

fix sleep cleanup

---

lua/core/menu.lua

Service state changes before this change when executing `reset` via the menu:
```
Mar 08 23:52:03 norns systemd[1]: plymouth-read-write.service: Cannot add dependency job, ignoring: Unit plymouth-read-write.service is masked.
Mar 08 23:52:03 norns systemd[1]: plymouth-start.service: Cannot add dependency job, ignoring: Unit plymouth-start.service is masked.
Mar 08 23:52:03 norns systemd[1]: Stopped target norns.
Mar 08 23:52:03 norns systemd[1]: Stopping norns.
Mar 08 23:52:03 norns systemd[1]: Starting norns-init...
Mar 08 23:52:03 norns systemd[1]: Stopping norns-sclang.service...
Mar 08 23:52:03 norns systemd[1]: Stopping norns-crone.service...
Mar 08 23:52:03 norns systemd[1]: Started norns-init.
Mar 08 23:52:03 norns systemd[1]: Stopped norns-sclang.service.
Mar 08 23:52:03 norns …
```

Remove redundant restarts

---

crone/src/Tape.h

issue #739 
re-wrote, doublechecked and cleaned up multithreading bits.
in particular, more correct signaling. tried lockless variant but simply didn't work. lock doesn't block audio thread.  
ringbuffer correctly reset on open
i can no longer reproduce the garbage fire meltdown on norns HW. there are still occasional overruns while writing - these will result in dropouts. no longer printing anything on overruns because we don't actually want to exacerbate glitches with I/O on audio thread.
time permitting, will come back to this with a clean test case and maybe ask for help from LAD community.

fix tape (2nd try)

---

crone/src/Utilities.h

tiny change to increase default convergence time for log smoothers, from 1ms to 50ms. 
motivation: issue #750 
note that this effects everything that uses `LogRamp` - softcut rate, &c. there are explicit OSC commands to change smoothing time for mix levels, softcut levels, &c - but this is probably a better starting place.

change default logarithmic ramp time from 1ms -> 50ms

---

sc/core/Crone.sc

i'm here just adding a flag that determines whether to boot on sclang init (the default is true which is normal norns behavior). this simplifies using Crone on desktop sc work in conjunction with non-Crone stuff.
Ie. if I do not want Crone to boot automatically I put this in my startup.scd file:
```
Crone.bootOnInit = false;
```

add crone boot flag

---

crone/src/OscInterface.cpp
crone/src/SoftCutClient.cpp
crone/src/SoftCutClient.h
matron/src/weaver.c

fixed a couple lua/OSC commands:
`/softcut/buffer/clear` : this was broken in `SoftCutClient`
`/softcut/buffer/clear_region_channel` : this was broken in `matron/weaver`
added:
-  `/softcut/buffer/write_mono [sffi]`; args: path, start (seconds), dur (seconds), channel (zero-based)
-  `/softcut/buffer/write_stereo [sff]`; args: path, start (seconds), dur (seconds)
for all the buffer functions, `dur=-1` means to read/write/clear the entire buffer. (or, read the entire file if that is shorter.) (there is an attempt in `OscInterface.cpp` to provide defaults for missing arguments, but it turns out `liblo` doesn't work this way and the handlers aren't called at all. so this should be cleaned up too.)
have **not** yet added lua/weaver glue for write commands, nor tested on norns HW (only on …

softcut buffer fixes

---

matron/src/hardware/gpio.c

Set out to implement GPIO retries, ended up with quite a big change.  Tested all keys and encoders work properly after this change. It fixes my problem that norns wasn't booting into matron correctly without mucking up the init scripts with ugly fingers-crossed pauses.
I see the following lines in output from journalctl -u norns-matron:
-- Logs begin at Sun 2019-03-17 21:36:27 +07, end at Sun 2019-03-17 21:44:17 +07. --
Mar 17 21:36:35 norns systemd[1]: Started norns-matron.service.
Mar 17 21:36:36 norns matron[322]: *** WARNING *** The program 'matron' uses the Apple Bonjour compatibility layer of Avahi.
Mar 17 21:36:36 norns matron[322]: *** WARNING *** Please fix your application to use the native API of Avahi!
Mar 17 21:36:36 norns matron[322]: *** WARNING *** For more information see …

make matron retry for 10s to grab gpios on boot

---

lua/core/menu.lua

Super small change to not turn wifi off on shutdown.
Note that this doesn't mean wifi will necessarily be turned on when starting, it'll be in the same state it was when shutting down.

Don't turn wifi off on shutdown

---

lua/core/config.lua
lua/core/menu.lua
lua/core/paramset.lua
lua/core/script.lua
lua/core/state.lua

this PR reverts the `dust` structure to 190303
```
dust/
audio/    -- all user audio
data/      -- user pset/pmap data, gets tree'd same as script folder
code/    -- user scripts/projects/etc. (includes 'we'/etc)
```
example script folder
```
mlr/
mlr.lua    -- main version, shows up as MLR
mod.lua   -- alt version, shows up as MLR/MOD
data/
mlr.pset    -- default pset. script is responsible for copying it/etc
other.data   -- whatever other data
lib/
sub-mlr-lib.lua  -- arbitrary lib, imported via require 'mlr/lib/sub-mlr-lib'
some-engine.sc   --- engine file
some-engine.lua   --- engine lib, require 'mlr/lib/some-engine'
```
i'd like to bundle this in to a new beta installer soon so people don't sit with the botched 190314 for long. but please let me know if there are outstanding …

revert data folder

---

matron/src/oracle.c

so far, one very small change patches a very dumb memleak in `oracle`

Fix memleaks

---

sc/core/Crone.sc

without this change, a misspelled or missing engine name causes the script to hang on "loading..." forever

warn and continue on nonexistent crone engine

---

lua/core/startup.lua

instead of `require`
- relative path to current file (provided by `norns.state.path`) (not 
- `.lua` extension not required

change include function

---

matron/src/events.c
matron/src/weaver.c

So I learned to use valgrind today, what a brilliant tool!
Think the change to events.c is just a garden variety forgot-to-free (I had a good ferret around to look where else the main event data structure might be freed, couldn't find anything)
The change to weaver.c is a bit more subtle - looks to me like lo_message_add_double leaks.  We can report this upstream separately with a minimal testcase but I'm happy to simply change to lo_message_add_float.
For evidence these are genuine leaks see valgrind before and after the changes - I can produce a third dump showing that the weaver.c change makes a difference if it seems far-fetched...
before:
https://gist.github.com/ranch-verdin/a403453ee4d8ef177e79eabe6798f6e7
after:
https://gist.github.com/ranch-verdin/d35eb7c7f709e5918ab937c0751afb30

Fix one obvious leak and one not-so-obvious one

---

sc/norns-config.sc

This was the only warning I ran into when running the included/default scripts
```
Mar 22 00:44:45 norns ws-wrapper[351]: WARNING: Could not open directory: '/home/we/norns/sc/abstractions'
```

SC remove abstractions includepath

---

lua/core/menu.lua

when experimenting with softcut (playback rate) and at times with other scripts using the generic params menu i've found myself wanting a fine adjustment mode.
this change is a rather basic solve; if key 3 is held down, the delta value from enc 3 is somewhat arbitrarily divided by 20.
some downsides of this approach that i see:
- the fine divisor is arbitrary and results in floating point values being sent to `param:delta(...)`
- parameters may benefit from being able to define course vs fine steps (like octaves vs semitones)
- the fine adjust behavior is only exposed when interacting in the menu but a script would have to roll its own.
if there is general interest in exposing fine parameter control as part of the param abstraction then i'm inclined to close this and look at a general …

WIP: fine parameter adjustment

---

matron/src/main.c

@artfwo pointed out my GPIO patch breaks desktop builds.  I think the best thing for now is to simply disable GPIO init when cross-compiling for x86 desktop (unless someone gets round to https://github.com/monome/norns/issues/732)
This is a bit of a hack but does fix the pressing issue (and I briefly tested it works for both platforms). Not quite sure what would be a better way to approach this?  I looked around for some global header where we could put in a more explicitly named preprocessor macro (eg #define DESKTOP_CROSSCOMPILE) but appears there is no project-wide header file for matron.

don't hang for ages waiting for gpio unless on norns hardware

---

matron/src/args.c
matron/src/args.h
matron/src/hardware/screen.c

added `matron` argument for specifying path to framebuffer used by cairo
defaults to `/dev/fb0`
change it like so:
`matron -f/dev/fb1`
have only tested on norns to make sure nothing is broken. @okyeron (or anyone else requiring this feature) - would be great to get feedback before we merge
addresses issue #749

framebuffer select argument

---

lua/core/startup.lua

many apologies for the breakage!
`include(file)` now includes from `dust/code` (and appends `.lua`)
previously was including from current folder (ie `dust/code/awake`) which made cross-folder sharing difficult (ie for engine libs)

change include() path

---

lua/core/startup.lua

for `include(filepath)`:
- first check local ie `dust/code/awake/(filepath).lua`
- second check root folder = `dust/code/(filepath).lua`
thanks @catfact

include() checks two paths

---

lua/core/startup.lua
matron/src/oracle.c

fix a dang null-terminator bug that crashed matron sometimes on engine report.
also, report engines on startup, because why not
fixes issue #798

fix crash in engine report (strlen), report engines on startup

---

lua/core/script.lua
sc/core/CroneEngine.sc

addresses issue #615 by simply adding an empty engine called `Engine_None`.
test script: `no_engine.lua` 
```
-- engine.name = nope
local p_amp_l = poll.set('amp_in_l', function(amp_l) print("amp L: "..amp_l) end)
local p_amp_r = poll.set('amp_in_r', function(amp_r) print("amp R: "..amp_l) end)
p_amp_l:start()
p_amp_r:start()
end
```

add dummy engine; allows scripts to use polls w/o an engine

---

crone/osc-methods.txt
crone/src/OscInterface.cpp
crone/src/SoftCutClient.h
crone/src/softcut/SoftCut.h
crone/src/softcut/SoftCutVoice.cpp
crone/src/softcut/SoftCutVoice.h
lua/core/softcut.lua

function to add offset to the phase quantization calc.
helpful for loops that don't start at position 0 (or a nice multiple thereof), needed for mlr
(also commented out osc packet prints)

softcut phase offset

---

lua/lib/fileselect.lua

in the fileselect module (used by TAPE and any other file selector (mlr))

display NO FILES for empty folder

---

lua/core/audio.lua

Since ldoc only parses comments beginning with 3 hyphens, `level_monitor` wasn't showing up in norns docs. Currently, the only way to discover this function is to read the source.

docs: fixes audio.level_monitor() ldoc

---

crone/osc-methods.txt
crone/src/Commands.h
crone/src/MixerClient.cpp
crone/src/MixerClient.h
crone/src/OscInterface.cpp
lua/core/audio.lua
lua/core/mix.lua
matron/src/oracle.c
matron/src/oracle.h
matron/src/weaver.c

So far this PR
* adds tape->cut and tape->aux level params to the crone mixer, initialized to 0 / -inf dB
* exposes tape->cut and tape->aux as OSC endpoints
* adds tape->cut and tape->aux methods to the Audio module in matron
* adds `rev tape input` menu param to `system > audio`
Tape to reverb works great. There's no direct UI exposure of the tape->cut parameter; I was able to test it by running `local audio = require('core\audio') audio.level_tape_cut(18.0)` in the maiden console. This is pretty fun, it ends up being a back door way of getting recorded material into mlr.
Making the tape->cut default to unity gain would make this step unnecessary, but that seems like a breaking change for people who want to play a backing track unaltered while sampling live input. Not sure if this should …

tape->cut and tape->reverb routing options

---

lua/core/menu.lua

Currently there is no way of calling menu from script (eg. for entering menu from keyboard).

norns.menu.toggle() function added

---

lua/core/mix.lua

crone compressor uses seconds, lua uses milliseconds but wasn't converting them

fix compressor timing (sec/ms mismatch)

---

lua/core/engine.lua

Simply added  ` Engine.name = name` to `Engine.load`
Works ok with engine switching script (modified from [here](https://github.com/neauoire/tutorial/blob/master/A_engine.lua)). Not sure if this impacts anything else as @catfact [mentions here](https://llllllll.co/t/norns-development/14073/334)

set name in engine.load

---

lua/core/engine.lua

this makes it so that `engine.load()` will skip issuing a load command if there's already one pending. (the function will also return `false` in this case, and `true` otherwise.)
also cleaned up some bad-looking logic in engine-loaded callback, which was conceivably responsible this apparent bug: incomplete command table at script init time, when engine takes long time to load, and no script-level callback is defined.
(https://llllllll.co/t/timber/21407/70)

add engine loading status flag

---

lua/core/params/control.lua
lua/core/params/file.lua
lua/core/params/number.lua
lua/core/params/option.lua
lua/core/params/taper.lua
lua/core/paramset.lua

minor feature addition
```
params:set(index, value, silent)
```
where `silent` is optional. if it is anything except for `false` the `bang` (`action` function) will not be called.
@markwheeler

param set silent

---

lua/core/softcut.lua

i don't necessarily know if this is a great idea, but leaving it here.

make backwards-compatibility wrappers around pre_filter

---

lua/core/startup.lua

per #788 this moves `wifi.init()` into the `norns.startup_status.ok` callback function - at which point `wifi.state` gets set properly and the norns screen does not display `-` for IP address after reboot.

move wifi-init

---

lua/core/menu.lua
lua/core/startup.lua

instead of AUDIO ENGINE error, now we see DUPLICATE ENGINES and then the duplicates are printed out in maiden.
fixes #864

report duplicates, improve missing include warning

---

wscript

there is currently some include path hackery going on within the norns buildroot setup when it comes to checking for supercollider headers and building plugins. this additional configuration flag should allow the buildroot setup to be streamlined (allow the path to supercollider in the cross compilation environment to be passed in).
note that i've removed the absolute and partially redundant include paths for `/usr/local/include/SuperCollider...` and `/usr/include/SuperCollider` and replaced them with paths that start with and explict SC_PREFIX value
the default for `--supercollider-prefix` is `/usr` so things will still compile on the current norns device(s) and likely any Linux hosts with supercollider installed via a package. 
/cc @simonvanderveldt

add --supercollider-prefix config option

---

crone/src/SoftCutClient.cpp

It looks like the order of the `src` and `dst` args was reversed. Hopefully this fixes it.
Docs:
https://monome.github.io/norns/doc/modules/softcut.html#SC.level_cut_cut

Match SET_LEVEL_CUT_CUT arg order to docs/API (#874)

---

lua/core/audio.lua

previously had `_path.dust` built-in which basically makes this difficult to use.

audio.file_info() now uses absolute path

---

crone/src/softcut/SoftCutVoice.cpp

first of several small PRs around crone levels.
here, softcut reset was erroneously setting both lowpass and dry pre-filter routes to full volume. this halved the headroom for clipping at the buffer input.
solution taken here is to use only the dry route. this means rate->filter modulation will not be apparent without explicitly setting filter mode levels. but i think this is actually the right default - otherwise users are surprised by any phase shift or &c introduced by the filter even when fully open.
also, the default RQ value of 20 was a little silly.

initialize all softcut filters to fully dry, reasonable bandwidth

---

crone/src/Bus.h
crone/src/SoftCutClient.cpp

use equal power panning when mixing softcut voices to output bus.

Softcut equal power pan

---

matron/src/device/device_crow.c
matron/src/weaver.c

`device_crow.c` was throwing unused-result errors.
suppressed with gcc pragma.
gave weaver.c same treatment while i was thinking about it, removing some `(void)l` clutter. 
also, device_crow.c was an unholy mix of 2-space and tabs. uncrustified.

Cleanup device_crow

---

lua/core/crow.lua

user can now redefine the remaining crow receive (instead of just default printing it)
```
crow.receive = function(x) print("ahhhhh! " .. x) end
```
it will be reset on cleanup/init

user crow receive function

---

crone/src/SoftCutClient.cpp
crone/src/Tape.h

added hardclipper in tape writer class. 
out-of-range values were wrapping when encoded to fixed point. (seems like pretty bad behavior from libsndfile, but w/e.)
could probably implement the hardclipper more efficiently, without conditionals, but this will get it done.

Fix clip before tape write

---

lua/core/menu.lua
matron/src/device/device.c
matron/src/device/device.h
matron/src/device/device_common.h
matron/src/device/device_list.c
matron/src/device/device_midi.c
matron/src/device/device_midi.h

Trying to fix #536 but this has issues:
- ~~MIDI device selection list not growing with ports~~
- ~~Unplugging devices doesn't remove them correctly~~
- Includes are dirtier
- Device list code is generally dirtier
- Probably needs more error logging
- I'm a C noob so I may have added memory leaks
- I'm a C noob so the code style is probably off

Support multiple ports per MIDI device

---

lua/core/menu.lua

`TAPE_REC_STOP` was being accessed before decl  (in `m.key[pRESET]`).  i would expect this may have been causing problems but didn't test to verify.  (don't really use tape myself...)
otherwise, there were a few unused locals i removed too.   and a leak of `y_offset` as well.
/cc @tehn

unused vars,  leaked global, local constant decls

---

lua/core/menu.lua

file select now doesn't jam the lua scheduler.
also gives a "scanning..." message if you have tons of files, and "no files" if you killed your folder
partial fix #909

async file select scan 

---

lua/core/crow.lua
matron/src/device/device_crow.c

crow detection previously failed if input streams were on (flooding serial input so the `^^id` is lost)

fix crow detection

---

lua/core/crow.lua

match syntax with native crow
`output[1].execute` is now `output[1]()`

crow asl execute syntax

---

lua/core/menu.lua
matron/src/system_cmd.c

due to a subtlety of the pthreads API, the worker threads created in `system_cmd.c` were leaking _all the memory_ of the child processes they spawned. 
(the child process in latest version being a big ol' `find` that ate up a rather shocking 10MB a pop with a goodly number of scripts installed. [um, actually that's not quite right. it's mapped but unwired, or something.])
detaching the thread fixes this, it seems.
also uncrustified that file, because _someone_ has their vim set on 2space again. :)

Fix system cmd memleak

---

matron/src/system_cmd.c

2nd look at `system_cmd.c`
i'm now reasonably sure this will not bork even when command output massively exceeds buffer capacity. (it will truncate to the last complete line that fits in the buffer.)

System cmd more cleanup

---

lua/core/crow.lua

`crow.connected()` returns true/false
fixes #892

crow connect status function

---

matron/src/system_cmd.c

okey dokey,
`system_cmd.c` continues to expand its collection of extravagant comments.
probably fixes #925 which i can't reproduce; someone with rpi4 needs to test. OG norns seems fine.

copy 1 less byte with strncpy and let it null-terminate. fixes #925,

---

lua/core/crow.lua

This brings norns syntax in-line with native crow syntax for interacting with a running ASL sequence.
The syntax is:
`output[channel](<directive>)` where `<directive>` is a string such as "attack" or "release" in order to allow richer interaction with an existing ASL declaration.
In addition this change means you can pass an ASL directly into the table call to both set the `.action` & begin the ASL:
```
-- current syntax
output[channel].action = 'lfo()'
output[channel]()
-- with this PR
output[channel]( 'lfo()' )
```
This is identical to how it works in a crow-native script.

extend crow.output[]() to accept directive strings

---

lua/core/script.lua

globals reset caused errors when globals were referenced in cleanup, ie. https://github.com/tehn/ash/blob/master/playfair.lua#L268. to recreate, load `playfair` script, then another script and check lua output: "### cleanup failed" is printed. `playfair.data` is never saved.
PR moves globals reset after cleanup and prints actual error thrown in `pcall(cleanup)`

move global reset after cleanup, better error logging

---

lua/core/menu.lua

my bad - tried using `ls -R` instead of `find` to search scripts, didn't realize it somehow is not recursing on norns (though seems to work on my archlinux install! most odd.)
reverting to the previous `find` command for now. this is much slower and more memory-hungry - i suspect because it doesn't skip hidden directories and so is searching through the `.git` tree in every project.
i tried some variations with `find ... -path ... -prune` but couldn't get it to work. maybe someone with more advanced bash-fu can suggest an alternative.

revert using 'ls' instead of 'find'

---

matron/src/clocks/clock_internal.c

In the comments of #712 both @okyeron and I observed `clock_internal_set_tempo` not having any effect on the internal source for the coroutine clock.
There was one additional cast overflow issue in `clock_internal_run`. Both `req.tv_sec` and `req.tv_nsec` are signed integers and require casts. With this change, I can set the coroutine clock source interactively from script. 
Without this change, calls to `clock_internal_set_tempo` have no effect. Here's some investigation history:
<details>
<p>With the following logging additions to `clock_internal.c`:</p>
```
diff --git a/matron/src/clocks/clock_internal.c b/matron/src/clocks/clock_internal.c
index dcb7775..f22eaa5 100644
--- a/matron/src/clocks/clock_internal.c
+++ b/matron/src/clocks/clock_internal.c
@@ -9,29 +10,42 @@
#include …
```

Fix current_time overflow and allow clock_internal_set_tempo to work

---

matron/src/oracle.c
sc/core/Crone.sc

when working with Crone polls solely in SuperCollider (ie. when trying to debug poll values using an OSCFunc with the same sclang interpreter that Crone is running on) the fact that the oscpath for explicitly requesting values and the oscpath for the poll value callback is the same would cause infinite ping ponging of messages back and forth.
for this reason i suggest to discern the request by changing its oscpath to `/poll/request/value` (actually what's in the sc code documentation).

change request poll value osc command

---

lua/core/encoders.lua
lua/core/menu.lua

fixes #414 
```
norns.enc.sens(0,4)
norns.enc.accel(0,true)
```
sets script sensitivity to 4 and accel on for all encoders.
menu restores state when moving between menu and script

user scripts can set encoder attrib

---

lua/core/menu.lua

fixes #952 
clear screen before entering PLAY.
if script's `redraw()` has an error, the menu screen wouldn't get cleared which is very confusing.

clear screen before entering PLAY

---

lua/core/params/option.lua

param menu sends fractional deltas, which broke tOPTION
fixes #953

do not allow fractional tOPTION index

---

lua/core/engine.lua

fix other issue raised in #952 
where an error in `refresh` if called by `init` will fail before setting engine status, which then makes loading another engine never happen again.

update engine status early

---

crone/CMakeLists.txt
crone/src/BufDiskWorker.cpp
crone/src/BufDiskWorker.h
crone/src/MixerClient.h
crone/src/OscInterface.cpp
crone/src/PeakMeter.h
crone/src/SoftCutClient.cpp
crone/src/SoftCutClient.h
crone/src/main.cpp
crone/src/softcut/SoftCutHead.cpp
crone/wscript

redo of #958. 
not sure what happened there, but possible weirdness with nontrivial `std::string` copy constructor usage in `spsc_queue` on ARM. this situation doesn't actually need to be lockfree so just replaced spsc_queue with mutex. (note the FIXME: this means we can replace worker `sleep` with a condvar, but it's a long sleep and its fine for now)
this also brings in small fix for read destination max frame count.
there are quite a few debug statements in the disk worker module. leaving for now, will remove before merge.

Buf worker fixed

---

maiden/src/io.c
maiden/src/io.h
maiden/src/ui.c

fixes #978 
this is a minimal change that allows the original curses based `maiden` to work along side the web based version. through the magic of nanomsg both the console repl and the web repl work at the same time. input is not echoed to each repl but each repl does see the same output.
_note: to compile i needed to `sudo apt-get install libncursesw5-dev`_
an outstanding issue which this PR doesn't address is the duplicate command names. perhaps it is worth reimplementing this in go and rolling it into the maiden backend command as `maiden repl`. one advantage of integrating it in the go based command would be the ability to run it on a different host (along side a non-web based editor).

curses maiden ws compat

---

lua/core/script.lua
sc/core/CroneEngine.sc

when debugging an issue i noticed engine free routine is called two times due to `_norns.free_engine()` in `script.lua` (looks like it isn't needed since engine is deinited in sc code here: https://github.com/monome/norns/blob/master/sc/core/Crone.sc#L109-L115)
also, since `CroneEngine.deinit` is already called in a routine (see https://github.com/monome/norns/blob/master/sc/core/Crone.sc#L108) i removed the `fork { }` wrapping code in CroneEngine.deinit.
(... my original issue was due to multiple forks and server.sync calls stalling sclang, so thought it might be good to do this clean up)

cleanup engine deinit logic

---

lua/core/startup.lua

checks for file `~/reverse.txt` and executes some jack rewiring if it exists.

stereo reverse mechanism

---

lua/core/softcut.lua

should be SC.VOICE_COUNT not SC.COUNT
yes ?
(did not build to test but confirmed error on my device)
```
/home/we/norns/lua/core/softcut.lua:201: 'for' limit must be a number
stack traceback:
/home/we/norns/lua/core/norns.lua:126: in metamethod '__index'
/home/we/norns/lua/core/softcut.lua:201: in function 'core/softcut.defaults'
/home/we/dust/code/wrms/lib/softloop.lua:2: in main chunk
[C]: in function 'dofile'
/home/we/norns/lua/core/startup.lua:39: in function 'include'
/home/we/dust/code/wrms/lib/lib_wrms.lua:10: in main chunk
[C]: in function 'dofile'
/home/we/norns/lua/core/startup.lua:39: in function 'include'
/home/we/dust/code/wrms/wrms.lua:9: in main chunk
[C]: in function 'dofile'
/home/we/norns/lua/core/script.lua:154: in function </home/we/norns/lua/core/script.lua:154>
[C]: …
```

fix softcut.defaults()

---

lua/core/softcut.lua

this PR is two things.
first, makes `softcut.defaults()` functional, and synchronized with actual default values defined in the backend `reset` functions.
second, add lots of ldoc stuff to the `softcut`. (mostly function and parameter descriptions, but also little things like replacing `@classmod` with `@module` to remove the erroneous colons in ldoc output.)
this is WIP: i can't actually test today, and i haven't added docstrings to every function.

fixes to softcut.defaults(), and lots of docstrings

---

matron/src/device/device_list.c
matron/src/device/device_midi.c
matron/src/device/device_midi.h

i spent a bit of time trying to get to the bottom of #920 - in particular looking at the changes which were made to the device management for handle multiple midi endpoints.
i believe the problematic change was the introduction of `dev_remove_node`. the `dev_remove_node` function combined existing deletion event posting, `dev_delete`, and device list node removal _with a call to `dev_lookup_path` starting from the device list node being removed/deleted_. the `dev_lookup_path` function walks the device list looking for the first node which matches the given path. in the case of `dev_remove_node` that lookup was started from the device node which was previously passed to `dev_delete`. the `dev_delete` function does several things but in particular it frees memory allocated for the device …

likely fix for SEGV on USB device removal

---

lua/core/menu/reset.lua
lua/core/menu/update.lua
lua/core/norns.lua

extract common `reset` logic.
secondary motive: make it easier to reset audio from the repl; though maybe added `;reset` sugar would be even better still?
/cc  @tehn

extract reset

---

lua/core/screen.lua

i use this in my scripts so would be good to use it from `screen` global rather than `_norns.screen_extents`.

expose extents

---

matron/src/weaver.c

`weaver.c` had wrong order of arguments when sending the command to clear specific region of single channel in softcut buffer.

fix wrong order of arguments for clear_buffer_region_channel

---

crone/src/BufDiskWorker.cpp

this typo made it so that remainder frames (up to the final 1024) were being skipped with an error when executing read-buffer commands.

fix skipped remainder frames in read-buffer commands

---

lua/core/menu/devices.lua
lua/core/menu/reset.lua
lua/core/menu/system.lua

- SYSTEM > RESET now does a dirty shutdown (no script run on startup) and erases pset/state data (to assist users getting into a sane state re: levels and vports)
- remove unneeded state saves

more complete reset

---

lua/core/grid.lua

Found a situation where grid vports was reporting rows/cols values when that vport was set to `none`.
Test situation:
- with all grid vports set to none, attach grid.
- remove grid and set vport 1 back to none
- `tab.print(grid.vports[1])` then returns the following:
```
cols	16
name	none
all	function: 0x1f79248
led	function: 0x1f6bd98
rows	8
refresh	function: 0x1fa7e60
intensity	function: 0x1fa8548
rotation	function: 0x1fa8590
```
Thus `name` is set to none, but `rows` and `cols` are not reset to zero
Can also be tested with my [Grid Test script](https://llllllll.co/t/grid-test/29346) in the lines Library when manually changing grid port positions.
Proposed fix: reset rows/cols to zero in Grid.update_devices()

grid vports not removing rows/cols on update_devices

---

crone/src/BufDiskWorker.cpp

WOOPS. stereo variant of buffer write function was ignoring source position. very simple fix.
attaching test script and audio file
[softcut-buffer-write-pos-test.zip](https://github.com/monome/norns/files/4261249/softcut-buffer-write-pos-test.zip)

fix source position for stereo buffer write

---

ws-wrapper/src/main.c

avoids printing the tx side of the ws-wrapper traffic to stdout. 
- reduces pressure on the linux logging infrastructure
- allows running commands like `journalctl` and `dmesg` using `os.execute(...)` in the maiden repl without getting doubled output

remove logging of ws tx traffic

---

lua/core/norns.lua
matron/src/hardware/gpio.c
matron/src/main.c
matron/src/watch.c
matron/src/watch.h
matron/wscript

further fixes #1014 
in sequence, hold K3, K2, K1. if 10s elapses, services are restart.
however, weird thing i'm seeing:
despite `systemctl restart norns-*` it seems like only matron is being restarted? ie, i don't get the startup animation and things start almost immediately. running the same command on the command line does what we want?

keystroke activated watchdog

---

lua/core/audio.lua
lua/core/paramset.lua

added a param flag for saving to pset (or not)
in this case, we wanted _not_ to save mixer levels in the pset
```
params:set_state("output_level", false)
```
etc. by default now the levels are not saved. i did not extend this to reverb/comp params.
i think this is fine by default, but i suspect there's going to be a request (which is reasonable) that all params get some sort of top-level UI for save-to-pset or not (like the aleph, which was a powerful feature).

pset save flag per param

---

third-party/wscript

this will silence pages of warnings like
```
/usr/include/c++/6/bits/stl_algo.h:112:5: note: parameter passing for argument of type ‘__gnu_cxx::__normal_iterator<std::pair<ableton::link::PeerState, asio::ip::address>*, std::vector<std::pair<ableton::link::PeerState, asio::ip::address> > >’ will change in GCC 7.1
```
when building link bindings with gcc 6.

add -Wno-psabi to link wscript

---

lua/core/wifi.lua

Currently the hotspot ssid / password are hard coded to "norns" / "nnnnnnnn"
In a situation with multiple devices, having the script pick up the device hostname instead would be nice. Mostly applicable to someone with norns + shield, or shield + shield, etc.
I've added a variable `hotspot_password` but I'm not sure if there's a better place to establish that. For the moment it's local to `wifi.lua`. (also not sure if there's a preferred variable naming scheme I should use).

Use device hostname for wifi hotspot ssid

---

maiden-repl/README.md

adds some information about how to get started with `maiden-repl` on alternate hosts.

add maiden-repl README with build instructions

---

matron/src/clocks/clock_link.c

fixes #1064
this PR doesn't implement sending start/stop commands to link, it could be done separately.
this implementation doesn't reset link beat counter.

enable start/stop sync for link clock source

---

lua/core/osc.lua

fixes https://github.com/monome/norns/issues/1023
added the `/remote/` OSC pattern
- `/remote/key 2 1` --- effectively executes `key(2,1)` at the lowest level (menu or play mode)
- `/remote/enc 1 -3`
same OSC port: 10111
important to remember that with key remotes it should be treated like a state-ful toggle. ie, don't send a bunch of key-downs in a row. some menu/script logic may get super weird since a script could be tracking down-up positions.
@dndrks need some docs for this

osc remote for key/enc

---

lua/core/clock.lua
lua/core/state.lua

fixes #1078
- clock menu params don't save in pset
- clock menu params save in `system.state` so they persist between scripts and reboots
- fixed tempo consistency when switching between link/internal

clock param persist

---

lua/core/clock.lua

default arg is 1 (beat), so it also functions as a simple helper ie `clock.get_beat_ms(3/2)`
ie bpm 120 returns 500ms
mainly for use in other params that want ms values... ie softcut loop time or cut position

clock.get_beat_ms

---

matron/src/clocks/clock_crow.c
matron/src/clocks/clock_midi.c

fixes #1088
basically rewrote the averaging function somewhat needlessly, as the primary fix was tiny.
the main improvement is filtering out huge values: infer a clock stop/start.

filter crow/midi input

---

lua/core/clock.lua

this appears to be required in order for #1092 to function correctly.

pass coroutine args to initial resume

---

lua/core/clock.lua
lua/core/state.lua
matron/src/clocks/clock_crow.c
matron/src/clocks/clock_crow.h
matron/src/weaver.c

was default to 4 subdivisions. now it's settable via the param menu.
also removed "crow clear" as it was a stopgap fix for an improperly initialized crow, which was fixed in a recent PR
tested successfully.
@artfwo i know you don't have a crow, but thought you could just quickly glance at this

add input division for crow clock

---

lua/core/menu/params.lua
lua/core/paramset.lua

fixes #1086 
- default pset name is blank, so you can type your own
- it left blank, it will autofill the name with the script name
- pset name display as mixed case (previously all uppercase)
- clarify api docs for default param load
@papernoise

fix pset naming

---

lua/core/paramset.lua

helper function to list param id's.
i find myself doing ugly hacks in the REPL to find these, so better have a sanctioned method
these id's are also visible in the param menu when in MAP mode.
@dndrks you were asking for something like this last month, and i recall showing you a hack

params list

---

crone/src/MixerClient.cpp

this seems to have been a mistake, unless i'm forgetting something. 
this small change applies the softcut master level as soon as it comes into the mixer, instead of waiting until it is mixed to the insert bus.

move softcut master level before aux send

---

lua/core/crow.lua

This just replaces the `tostringwithquotes` function by the built-in `%q` option in `string.format`.
Just a code cleanliness thing because I saw this 'quoted string' option while doing some random googling. Felt more idiomatic to lua.

Remove custom function by using builtin string library

---

lua/core/menu/params.lua

I noticed `params:hide(index)` only works parameters at the top level, this allows hiding to work within groups as well.

hide params inside of group

---

lua/core/config.lua
lua/core/norns.lua
lua/lib/tabutil.lua

- makes `_path` global table read only
- adds public `paths` table which exposes _path and state related paths
- teach tabutil.readonly optional limit which keys are exposed

expose configured paths in read only table

---

lua/core/config.lua
lua/core/norns.lua
lua/core/script.lua
lua/core/state.lua

@ngwese after some use i propose some minor changes... basically to reduce the verbosity of the `shared` table:
```
paths.code
paths.data
paths.audio
paths.tape
paths.this.path
paths.this.data
paths.this.lib
```
this realistically covers all the needed paths, and puts the shared ones at the root level.
note, `_path` is no longer protected, but the global state gets reset in between loads...

path table

---

matron/src/hardware/screen.c

On GCC 9.3.0, the following warnings are emitted, failing compilation, when running `./waf`:
```
../matron/src/hardware/screen.c: In function `screen_init'
../matron/src/hardware/screen.c:251:53: error: `$s' directive output may be truncated writing up to 2143 bytes into a region of size 239 [-Werror=format-truncation=]
```
This rather nifty bit of static analysis is blogged about [here](https://developers.redhat.com/blog/2018/05/24/detecting-string-truncation-with-gcc-8/).
Also added some missing trailing newlines in some other `printf`s in this file.

handle snprintf truncation warning-as-error on recent gcc

---

lua/lib/pattern_time.lua

- include `overdub` in the constructor
- `overdub_event`: insert both `.time` and `.event`
- `overdub_event`: calculates previous step's time adjustment so total time after overdub remains the same

pattern time overdub

---

lua/core/crow.lua

`crow.connected()` would always return false, since there is never a value assigned to `_norns.crow.dev` (should be `norns.crow.dev`). Reported [here](https://llllllll.co/t/crow-help-general-connectivity-device-qs-ecosystem/25866/465).

fix crow.connected() always returning false

---

matron/src/device/device_crow.c

`dev_crow_send ` would `strcpy` the user input string into a 256 byte stack-allocated buffer and `strcat` a newline. Instead, this patch just `write`s the string to the crow fd and then `write`s a newline character. Previously, the following script would cause matron to crash due to a SIGABRT when crow is connected:
```lua
function repeat_str(s, times)
if times <= 1 then
return s
else
return s .. repeat_str(s, times - 1)
end
end
crow.send(repeat_str('0123456789abcdef', 32))
crow.send('print("crow ok")')
print('done')
end
```
With this patch the output is:
```
done
crow:	repl:1: malformed number near '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
crow:	123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789 …
```

avoid buffer overflow in dev_crow_send

---

lua/core/config.lua
lua/core/startup.lua

adds the ability to `include(...)` code from a third directory; `lua/extn`, within the norns code base.
aside: @pq it might make sense move the `asl.lua` code here and switch to using `include` instead of `require` (since the asl module is getting forcefully unloaded in the script handling code)

teach include() to find code in norns/lua/extn

---

lua/core/menu/params.lua
lua/lib/fileselect.lua

When editing a file param, navigates to the last folder where a file was selected, to allow quicker changing between sample files in the same folder. Suggested [here](https://llllllll.co/t/norns-sample-load-workflow-improvement/27296).

file params: navigate to last visited folder

---

lua/lib/container/TESTING.md
lua/lib/container/defaulttable.lua
lua/lib/container/defaulttable_test.lua

adds another container type to the core lib (and a small readme about running the tests)
inspired by python's "defaultdict" type which i've found very useful when trying to collate/correlate data. this combines nicely the `Deque` type in particular:
```
local Deque = require 'container/deque'
local DefaultTable = require 'container/defaulttable'
local events_by_channel = DefaultTable.new(Deque.new)
for _, ev in events do
events_by_channel[ev.ch]:push_back(ev)
end
```

defaulttable container type

---

lua/core/menu/params.lua
lua/core/menu/tape.lua
lua/core/params/file.lua
lua/lib/fileselect.lua

Fixes #1019 
* Adds a `../` directory entry when browsing a directory below the fileselect's root directory (/home/we/dust for file params, /home/we/dust/audio for tape). You now select this to go up a directory, and K2 instead cancels out of the file select menu completely.
* File select menus will remember the last folder where a file was selected, allowing quick selection of files in the same folder. This was also added to the TAPE > PLAY file selector. If a param value is already set, the folder containing that file will be opened. If no value is set, the last selected folder will be opened.
* For file params, added a `File:delta` implementation so that you can use E3 to scroll through files in the same directory as the currently selected file.

fileselect resume for each param and TAPE

---

matron/src/watch.c

very minor fix, but this has been bugging me.
`matron` compilation would fail under gcc 7 (unused return value, warning as error.)

fix warning/error

---

lua/core/softcut.lua

Luadoc indicates that the `amp` parameter to `softcut.level` is an `int`, but it is a `number`.
The other changes are because my editor settings strip trailing whitespace on save.

luadoc: softcut.level amp param: int -> number

---

lua/core/controlspec.lua
lua/core/params/control.lua
lua/core/params/number.lua
lua/core/paramset.lua

Fixes #1144 
Adds a `quantum` arg to controlspec which is used to define the fraction of the value range that `params:delta` adjusts by, rather than this being fixed at 1% of the range.
It is also sometimes useful to have params with values that wrap around rather than clamping, e.g. angles -- this is the case for the script I'm currently working on which is why I started messing with this. Added a `wrap` option to both `control` and `number` params.
Since this winds up being a lot of args on `ControlSpec.new` now I added a `ControlSpec.def` method which accepts a table -- I looked around a bit but I'm not sure what if any naming convention exists for positional vs keyword-argument style constructors. The table args for `ControlSpec.def` are `min` and `max` for consistency with …

add input quantum + wrap to controlspec, add wrap to number param

---

lua/extn/sky/unstable/io/norns.lua

previously the "norns" enc events used `num` for the encoder number field while "arc" enc events used `n`. this patch changes the "norns" enc event to use `n` (matching the arc event and bringing it more inline with the native norns api/docs).
fixes a wart noted by @csboling

sky: norns key/enc event use n to match arc

---

lua/lib/filters.lua

two minor changes to `filters.smoother`
- makes the `smoother` type/object definition local to the module
- removes debug print in `calc_coeff`
without the type being localized to the module i was running into weird undefined method errors for the `clear(..)` method on the metatable. i'm guessing this might have been caused by globals colliding.
whitespace changes are due to my editor removing trailing whitespace.

localize smoother type, remove debug print

---

lua/extn/sky/unstable/io/arc.lua

- allow ARC_DIAL events to be created external to gesture
- provide `is_dial` predicate
- clamp ArcDialRender segment to prevent poping
- provide `ArcDisplay.null_render()`

sky: unstable/io/arc improvements

---

lua/core/controlspec.lua

The quantum property isn't set when copying a ControlSpec causing errors when trying to alter params that copy a ControlSpec.
This can be seen when trying to change any of the Vol properties in playfair.

Fixed quantum not set when copying a ControlSpec

---

lua/core/menu/params.lua

Hope this is OK, I'm just getting familiar with lua and the norns source.
I noticed that if a script has file and number params, when you select a file parameter and come back out of the file selector the number params are much harder/slower to change. Fine value control is enabled when you go into the file selector but it isn't disabled when you come out.
This change disables fine control when coming out of the file selector.

Fixed: fine param value control after entering file select

---

crone/CMakeLists.txt

fixes for dev branch:
- all level envelopes in mixer are working again (i think)
- filter modulation is working (including shapes, SR divisor)
- fiter cutoff now specified using MIDI note for pre- and post-filters

Fix crone mixer

---

lua/core/script.lua

This is just a super minor irritation that arises due to my workflow -- if I'm SSHing from within emacs running on my windows machine, emacs decides to use windows line endings when I save a file, resulting in rectangles at the end of each line when viewing the script preview. The line endings don't make any functional difference besides this which is why I think stripping them here is reasonable, but it really should be something I'm able to fix on my end.... I have most certainly tried.

remove trailing carriage returns in script preview

---

lua/core/menu/tape.lua
lua/lib/textentry.lua

Fixes #1107 
- Checks if the next file exists when updating the tape index and advances until an available file is found.
- Adds a "check" callback parameter to `textentry.enter` that is called after each character is entered, allowing the caller to optionally show a warning message, in this case "FILE EXISTS"

protections from overwriting tape files

---

lua/lib/util.lua

I think this should address at least some of the issues people are having with `fileselect` crashing.
It addresses a mistake I made in not realizing that the Lua string functions aren't unicode-friendly. Long file names with multi-byte characters in them were causing issues when they needed to be trimmed in length to be displayed.

Fix for crash when trimming unicode strings

---

lua/core/softcut.lua

The previous Lua API for `buffer_render` made it difficult to use for requesting multiple buffer regions at roughly the same time, because the callback would get overwritten. This change just follows the same pattern as the phase poll, giving a separate function to set the callback.
FYI @okyeron -- I think you're maybe the only one besides me scripting with these functions so far.

softcut: use event_render to set render callback

---

update/update.sh

This change replaces the NULL byte with CRLF to avoid "./update.sh: line 56: warning: command substitution: ignored null byte in input".
See [this thread](https://llllllll.co/t/norns-file-structure-update-question/35859)

replace NULL byte with CRLF to avoid warning

---

update/update.sh

This fix removes rsyslog only if installed. This way the update script output is less confusing.
Inspired by [this post](https://llllllll.co/t/norns-file-structure-update-question/35859)

skip unnecessary rsyslog removal

---

lua/extn/sky/unstable/engine/polyperc.lua

nothing major, just some initial glue to allow use of `PolyPerc` in sky device chains similar to the existing `PolySub` glue.

sky: unstable device for polyperc engine

---

lua/core/midi.lua

matron posts midi data (from the device level) as soon as a device is attached regardless of whether or not the device is associated with a vport (which are only know to lua). the midi mapping logic provided by the menu tracks mapping assignments by vport (correct?)
this change ensures that the midi mapping logic is **_only_** provided events from devices with vport assignments. the previous logic would generate stack traces when midi from devices without port assignments is received.

only map events from devices with vport assignment

---

lua/core/menu/params.lua
lua/core/params/control.lua
lua/core/params/number.lua
lua/core/params/option.lua
lua/core/paramset.lua

some script parameters may not be suitable for live
manipulation via mapped midi controller. this change
adds an optional `allow_pmap` property to `Control`,
`Option`, and `Number` parameter types.
the `get_allow_pmap(...)` method on `ParamSet` will
return the property if set on the param otherwise it will
return `true` in order to retain existing behavior.
the menu code was changed to prevent access to the
MAPEDIT menu unless the `get_allow_pmap(...)` is `true`.

allow parameter mapping to be disabled

---

matron/src/device/device_common.h
matron/src/device/device_monitor.c

fixes a bug in cac8479fcc where crow devices were
mapped to the virtual midi device type (which has no
corresponding device file to watch for) because the
device pattern watch list did not match the order of
the `device_t` enum values.
fixes #1217

avoid monitoring device types without device files

---

lua/core/menu/tape.lua

not sure if this is really desired, but:
- currently, there is a check for `nil` file handle to `audio/tape/index.txt` when reading to increment tape filename.
- however, there is no analogous check for `nil` when writing to the same file a few lines later.
it is possible to run into this if a user deletes their `audio/` or `audio/tape/`. (why would they do this? don't ask me. but it happened and this burned some support time.)
so this change creates `~/dust/audio/tape/` and parents before writing the index file, if the initial attempt results in a `nil` handle.

create tape dir on record, if the user has deleted it

---

crone/src/SoftcutClient.cpp

`rec_offset` was being erroneously clamped to non-negative values.
now it is not clamped at all. (the final read/write indices are always wrapped to the buffer size anyways.)

don't clamp the record offset parameter

---

lua/core/menu.lua
lua/core/menu/home.lua
lua/core/menu/update.lua

fixes #1184 
also fixes incorrect re-initialization behaviors when K1 is short-pressed when script not loaded

fix menu lock behavior

---

lua/core/arc.lua
lua/core/grid.lua

fixes #1220 for specific device removals
note that global device removals was working fine (ie redefining `grid.remove` instead `g.remove`)

fix removal funcs

---

crone/src/SoftcutClient.cpp
lua/core/menu/home.lua
sc/core/Crone.sc

another pass at #1215, now correctly handling more cases for explicit engine deallocation from lua.

Cleanup engine deinit

---

lua/core/menu.lua
lua/core/menu/params.lua
lua/core/paramset.lua
lua/core/script.lua

remember last used pset per script, and if `init` contains `params:read()` (no args) it will load last pset, which is stored in `norns.state.last_pset` and the file is `dust/data/(SCRIPT)/pset-last.txt
fixes #1123 (the primary request at least... the other part is a more complex ask)

paramset default between sessions

---

lua/core/menu/params.lua
lua/core/params/binary.lua
lua/core/paramset.lua

i wanted to be able to map triggers to midi keys from a keyboard. @tehn suggested building off @andr-ew's "binary" parameter which does exactly what i need (and more!). it was so lovely to discover that this was extermely easy to do - only took about 45 minutes (including learning the codebase)! 
so here is my patch, which accomplishes this mapping to midi using the binary parameter. built off of and tested with script from @andr-ew (below).
i've never submitted a patch to norns before, i'm happy to follow guidance to make this kosher.
```lu
-- param test test
cs = require 'controlspec'
px = 48
py = 16
params:add{ type='binary', id='tog', behavior='toggle', allow_pmap=true, action=function(v) print('tog: ' .. tostring(v)) redraw()  end }
params:add{ type='binary', …
```

add midi mapping to binary param

---

lua/lib/util.lua

Shouldn't add 0.5 when using `math.ceil` - this causes e.g. 3.9 to get rounded up to 5.

Fix util.round_up

---

lua/core/menu.lua

fixes #1238 
bug introduced by #1227 which attempted to more properly implement a "menu lock" (ie, disable K1 when no script was loaded)
the menu logic is fragile. i would very much like to scrap the whole thing and start over.

menu mode fix

---

lua/core/menu/params.lua
lua/core/params/taper.lua

mapping of taper params was broken by 915c86ca85. this commit
restores mappability and includes taper params in the list of
control types which display their mapping in the menu (which
looks as if it was omitted from the list when the param menu
was reimplemented).
fixes #1241

allow taper params to be mapped (again)

---

lua/core/menu/home.lua
lua/core/menu/sleep.lua
lua/core/norns.lua
matron/src/hardware/battery.c
matron/src/hardware/i2c.c
matron/src/hardware/platform.c
matron/src/hardware/platform.h
matron/src/main.c
matron/src/weaver.c
matron/wscript

facilities to query the host hardware:
- CM3
- Pi3 (shield)
- "other" (not tested, but feasibly detectable)
this prevents irrelevant error messages from the battery and i2c on the shield, which though harmless looks alarming.
also allows customization of some menus:
- shield, don't show battery
- shield, give better shutdown message
lua helpers:
```
norns.platform -- 2=norns 3=shield
norns.is_norns -- boolean
norns.is_shield -- boolean
```
this could've been done with a config file, but i'd rather not have the user even worry about having the right config.
ps. i'll submit a followup pr which scrubs the hardware/device formatting, it's a little messy

platform checking

---

lua/core/screen.lua
matron/src/hardware/screen.c
matron/src/hardware/screen.h
matron/src/weaver.c

implementation example: https://github.com/northern-information/athenaeum/blob/main/rotate.lua
this works fine and good but i think we'll also want bunch of "rotate_rel" functions that cleanup after themselves?
```
screen.move(10, 10)
screen.rotated_text("i'm rotated ninety degrees", 90)
screen.move(10, 20)
screen.text("i'm not")
screen.move(30, 30)
screen.rotated_rect( ...
```

add screen rotate, translate, save, & restore

---

matron/src/device/device_midi.c

compilation has been broken for me on on gcc 9.3 for a while now, because of a stupid type warning. this trivial change fixes this annoyance.

trivial fix to compile on gcc9

---

doc/classes/screen.html
lua/core/screen.lua
matron/src/hardware/screen.c
matron/src/hardware/screen.h
matron/src/weaver.c

motivation came from a conversation at the weekly discord meetup.
someone brought up that the *cairo* C API had support for different blending modes/operators as shown here: https://www.cairographics.org/operators/
I wrote a short norns script for testing all of the operators
```
local a = {}
a[0]  = "CLEAR"
a[1]  = "SOURCE"
a[2]  = "OVER"
a[3]  = "IN"
a[4]  = "OUT"
a[5]  = "ATOP"
a[6]  = "DEST"
a[7]  = "DEST_OVER"
a[8]  = "DEST_IN"
a[9]  = "DEST_ATOP"
a[10] = "XOR"
a[11] = "ADD"
a[12] = "SATURATE"
a[13] = "MULTIPLY"
a[14] = "SCREEN"
a[15] = "OVERLAY"
a[16] = "DARKEN"
a[17] = "LIGHTEN"
a[18] = "COLOR_DODGE"
a[19] = "COLOR_BURN"
a[20] = "HARD_LIGHT"
a[21] = "SOFT_LIGHT"
a[22] = "DIFFERENCE"
a[23] = "EXCLUSION"
local i = 0;
redraw()
end
function enc(n, d)
i = util.clamp(i+d, …
```

Cairo blending modes

---

lua/core/menu/params.lua

This PR allows users to map `control` params with 'out' min/max values between 0 and 1 -- plus, it displays the output range using the controlspec for the param being mapped, so the user can choose scaled/warped values that match what they'd see in the params menu, instead of raw 0.0-1.0 values.
Resolution/precision is determined by the controlspec's `quantum` property, just like `params:delta()`.
`number` params work just like they did before.
I've been running this code since last weekend with no problems so far.
Fixes #1249, as mentioned in #1248.

Allow mapping control params over non-integer ranges

---

lua/core/menu/params.lua
lua/core/params/control.lua
lua/core/params/taper.lua

Fixes buggy fine control, and adds support for `taper` params by adding generic `map_value()`, `unmap_value()`, and `get_delta()` functions to the Control and Taper param classes. Figured it was best not to duplicate the taper math and instead break it out into separate functions that can be used by both the params menu and `get`/`set`/`delta`.

Further pmapping tweaks

---

lua/core/paramset.lua

i've been doing workarounds to get various params to act silently when reading new parameters. basically i have parameters that trigger reading parameters, and so it can get into loops when that parameters is banged upon reading. i implemented my own params_read using `silent` and it works fine, but i thought it might be worth adding in an option to the core to read parameters silently since it is already built into the `set` command.

allow params:read to read silently

---

lua/core/clock.lua
lua/core/menu/devices.lua
lua/core/menu/home.lua
lua/core/menu/params.lua
lua/core/midi.lua
lua/core/pmap.lua
lua/core/script.lua
lua/core/state.lua
lua/lib/util.lua

**previous behavior**:
- midi mappings (PMAPs) were only saved when a PSET was saved
**new behavior**:
- PMAPs are saved after they're assigned, so they persist between script loads without needing to save a PSET
**previous behavior**:
- norns could host up to 16 MIDI devices, but only assigned devices to 4 MIDI vports
- SYSTEM > DEVICES > MIDI reflected only 4 MIDI vports
- users had to remove/reassign vport-assigned devices more often
- this removing/reassigning disrupted accuracy of mapped controls in PMAPs (which restores based on vport device ID)
**new behavior**:
- norns can now assign up to 16 MIDI vports to match its hosting capability
- users can manage all 16 vports via SYSTEM > DEVICES > MIDI
- 16 device history means users will have to do much less device …

PMAP autosave + 16 MIDI vports

---

lua/core/norns.lua

useful for me but i won't be offended if this stretches the original intent to (and past) a breaking point.
tl;dr: if a script has already been cloned (or if it looks like it has because there's an existing directory with its name), do an actual `"fetch"`.
/cc @tehn

add pull to “fetch”

---

edge.sh
maiden-repl/wscript
wscript

- fixes `waf configure` dependency checking for `maiden-repl` (previously local conf checks and options weren't getting run)
- adds some additional robustness to `edge.sh`

minor build improvements

---

lua/lib/util.lua

i end up writing a function like this for just about every script. it is most often used to keep track of transport steps, but has other applications.
```lua
-- "cycle" back around to 1
util.cycle(17, 1, 16) -- 1 (first beat of 2nd measure)
-- recursive to handle "over cycling"
util.cycle(33, 1, 16) -- 1 (first beat of 3rd measure)
util.cycle(37, 1, 16) -- 5 (fifth beat of 3rd measure)
util.cycle(1024, 1, 16) -- 16 (last beat of 16th measure)
-- adjustable min if you want to confuse yourself
util.cycle(13, 2, 7) -- 6
util.cycle(13, 4, 10) -- 7
-- no change to a value within the range
util.cycle(1, 1, 16) -- 1
util.cycle(13, 1, 16) -- 13
```

constrain a positive number to a positive min/max range

---

lua/core/script.lua

I was exploring maiden and ran into an error. I created a simple `print("hello there")` script at `home/we/dust/untitled.lua` and got the following output when running it in maiden:
```
norns.script.load("untitled.lua")
lua: 
/home/we/norns/lua/core/script.lua:131: attempt to concatenate a nil value (field '?')
stack traceback:
/home/we/norns/lua/core/script.lua:131: in function 'core/script.load'
(...tail calls...)
```
So, I dug into the `Script.load` function in `script.lua` and got the general idea of what it was doing, but it was a bit confusing with the "hack for 3-deep subfol[d]ers" and all, so I tried to clean it up and got it working for my simple script. I could be missing some assumptions or cases the previous code was handling, but this seems correct.
I verified that various …

Fix nil value error in Script.load

---

ws-wrapper/src/main.c

this reverts PR #1028
yea or nay?
original problem:
- weird recursive duplicated output when you try and log the `matron` service from lua
- too many logs?
new problem:
- not enough logs?

ws-wrapper prints

---

lua/core/screen.lua

Following up on discussion [here](https://github.com/monome/norns/pull/1289#issuecomment-754287922). Also a couple whitespace normalizations in this file.

ldoc: explain format of screen.peek/screen.poke buffer

---

lua/core/clock.lua

tiny fix - clock "reset" parameter was passing `bpm` to `clock.internal.start()`. `bpm` being a nil value there, it didn't really matter but did obscure the intent of the code.
also fixed a stray pythonism in the clock help() demo code.

fix internal clock reset action, typo in help

---

lua/core/osc.lua

add option for the single-argument OSC patterns `/remote/[enc|key]/n d`  in addition to the 2-argument patterns `/remote/[enc|key] n d`.
this allows the remote function to be used with limited/inflexible clients like TouchOSC.
supercollider client code looks like this:
```
~norns_addr = NetAddr("norns.local", 10111);
~enc = { arg n, d;
~norns_addr.sendMsg('/remote/enc', n, d);
};
// other option:
~enc = { arg n, d;
~norns_addr.sendMsg(("/remote/enc/"++n).asSymbol, d);
};
~enc.value(1, 8);
~enc.value(1, -8);
```

Osc remote options

---

doc/modules/screen.html
lua/core/screen.lua

While trying to insert some special characters into my project i checked this part of the API to find only 14 font faces on norns. Later, the "Foundry"-App was pointed out to me, which made me aware of all the different fonts available.
I am not sure if the API-list was truncated on purpose, if not, here is a proposal for a complete list of fonts.

added missing fonts to api documentation

---

lua/core/menu/update.lua

added `releases.txt` which acts like a catalog
SYSTEM > UPDATE now queries this file (remotely, the live version on github, not the local copy)
normal update is exactly the same, checks against version.
if K1 is held when entering UPDATE, you are presented with two options: stable and beta, select-able with E2.
this allows forced re-update of stable, or installation of beta. theoretically this allows people to switch between both versions.
the backend is the same, ie update.sh. there will be no "reversion" of system-level changes (ie packages, systemctl units, etc), so we need to be aware about that going forward.
will do some additional testing when i get a non-dev unit, but initial tests show all is well.
ps. right now the `releases.txt` just has stable and beta pointing at the same …

update mechanism to install beta

---

lua/core/params/taper.lua

adds get_range() to the ``taper`` type param.
this would also make sense for ``control`` types, but i'm not sure how to get the min/max values from the controlspecs.

implements Taper:get_range()

---

lua/core/menu/params.lua

as mentioned in #1319 this change is meant to provide a way to refresh a menu screen manually when the visibility of elements change. this requires "rebuilding" the page/group menu to find newly visible/invisible elements. 
here is some test code that doesn't work without this change, but does work with this change.
```lua
-- test rebuild_params
params:add_option("switch","switch",{"a","b"},1)
params:set_action("switch",function(val)
params:show("param"..val)
params:hide("param"..(3-val))
if _menu.rebuild_params ~= nil then
_menu.rebuild_params()
end
end)
params:add_control("param1","a",controlspec.new(0,1,"lin",0.1,0.1))
params:add_control("param2","b",controlspec.new(0,1,"lin",0.1,0.5))
params:hide("param2")
params:add_group("grouped",3) …
```

add function to rebuild params after change in visibility

---

lua/lib/lattice.lua

this adds an api to do a "hard restart" in the lattice lib. this fixes a prospective problem if you stop and start a lattice. right now if you do `:stop()` followed by a `:start()`, you will most likely miss the first beat. here's an example with quarter notes at 120 bpm from running example code below:
```
start 232.149251708
qn1     232.149551916 <- first one starts on time
...
stop 234.389011044
start 236.568941924
qn1     237.323161172 <- after stopping this "restart" is delayed
```
one way around this is to do a "restart" which resets the clock, the transports, the patterns, etc. i call it a "hard restart" because it resets the clock. resetting the clock has the benefit to allow you to sync multiple scripts with multiple lattices on the same clock. but it does reset the clock so …

add hard restart to lattice

---

lua/core/menu/home.lua
lua/core/norns.lua
matron/src/event_types.h
matron/src/events.c
matron/src/hardware/stat.c
matron/src/weaver.c
matron/src/weaver.h

cpu monitoring was misleading ("it's only at 33%!") because it was an average of 4 cores
now the individual cores are shown. still has the average cpu available via `norns.cpu_avg` though the only place any of this is ever used is the alt-home screen.

monitor individual cpu cores

---

lua/core/menu/home.lua
lua/core/norns.lua
matron/src/event_types.h
matron/src/events.c
matron/src/hardware/stat.c
matron/src/oracle.c
matron/src/weaver.c
matron/src/weaver.h

this avoids a warning/error on some newer `gcc`s (`-Werror=incompatible-pointer-types`) for functions with `void*` parameters.

update OSC handler signatures

---

lua/core/paramset.lua

very small bug - skipping `binary` params with `trigger` behavior in the `params:bang()` loop, same behavior from the older trigger type

skip binary trigger in params:bang()

---

CONTRIBUTING.md
readme.md

I noticed a couple of broken links, and ran into a couple of issues on the contributing page in the process of trying to submit fixes.
One other bump I ran into:
Using `git clone` from the terminal seems to default to https (rather than ssh) so I needed to change the remote URLs - this step isn't accounted for in `CONTRIBUTING.md`. [GitHub docs here](https://docs.github.com/en/github/using-git/changing-a-remotes-url#switching-remote-urls-from-https-to-ssh)
Happy to add this step to the contributing doc if this is still the most straightforward path

fix lua api links and update references to 'main' branch

---

lua/core/paramset.lua

this PR addresses https://github.com/monome/norns/issues/1325
test code:
```lua
-- test
-- PSET read/write callbacks
-- press k2/k3 to write/read
-- try write/read with PSET menu
params:set_callback_read(function(filename)
print("finished reading '"..filename.."'")
end)
params:set_callback_write(function(filename,name)
print("finished writing '"..filename.."'")
end)
end
function key(k,z)
if z==1 and k==2 then
params:write("/tmp/parameters")
elseif z==1 and k==3 then
params:read("/tmp/parameters")
end
end
```
i'm not attached to the api names, lmk if i can improve it.

add callbacks for reading/writing parameters

---

matron/src/oracle.c

like #1323, but better
see also #1328 
can now build with both these toolchains:
`gcc (Raspbian 6.3.0-18+rpi1+deb9u1) 6.3.0 20170516`
`gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0`

Fix void pointer param again

---

lua/lib/util.lua

With `-L`, the `ls` command will treat symlinks to directories the same as "real" directories. Previously they did not get listed with the other directories and did not end in `/`, so the menu code would try to open them like files and error. This allows the user to e.g. `ln -s /media/usb /home/we/dust/audio/usb` and then play tape files / load samples from a USB disk.

fileselect: treat symlinks to directories like directories

---

lua/lib/lattice.lua

ping @tyleretters 
When doing a `hard_restart` on lattice, the `phase` has to be recalculated instead of taken from the `phase_end` property.
This way, multiple patterns stay in sync, after divisions had been changed.
`phase_end` can be removed as it's no longer used.
Also, a dedicated reset method was added to provide a handy way to start from t = 0, after changing divisions.
(coming from: kasperbauer/metrix#20)

Hard reset w modified divisions

---

matron/src/clock.c
matron/src/clock.h
matron/src/clocks/clock_crow.c
matron/src/clocks/clock_crow.h
matron/src/clocks/clock_internal.c
matron/src/clocks/clock_internal.h
matron/src/clocks/clock_link.c
matron/src/clocks/clock_link.h
matron/src/clocks/clock_midi.c
matron/src/clocks/clock_midi.h
matron/src/clocks/clock_scheduler.c
matron/src/clocks/clock_scheduler.h
matron/src/main.c
matron/src/weaver.c
matron/wscript

this PR replaces the multi-threaded coroutine resume event scheduler with a single-threaded implementation, where a single scheduler thread is constantly tracking scheduled sync and sleep wakeups with ~1 millisecond resolution and sending clock resume events when necessary.
effectively, this enables smooth(er) midi and crow beat tracking and smooth switching between clock sources when using the clock lib and fixes #1273.
i haven't done any proper benchmarking, but matron CPU usage seems to be roughly the same with this PR (with a few coroutines running concurrently), occasionally there's an increase from 4% to 5%, but it doesn't seem like a huge issue.

single threaded coroutine wakeup scheduler

---

matron/src/clocks/clock_internal.c
matron/src/clocks/clock_internal.h
matron/src/clocks/clock_scheduler.c
matron/src/clocks/clock_scheduler.h
matron/src/weaver.c

this is a simplified version of the internal clock that doesn't restart the tick thread when tempo is changed, providing smooth tempo changes with the new scheduler proposed in #1338
this implementation doesn't allow restarting the internal clock from a specific beat, as ticking happens in a constantly running thread, so it's only possible to reset the transport to beat zero (not that this feature was heavily used), so `clock.internal.start` in clock.lua has to be updated accordingly.

simplified internal clock implementation

---

lua/core/paramset.lua

solves for this edge case:
- start script + map a MIDI slider to a param
- reload script and send values from slider while script is starting
- incoming MIDI values cause (benign, but startling) script startup errors to be printed to matron as a nil param is passed

don't pass a nil param

---

matron/src/main.c

small change to ensure that scheduler doesn't try to get an uninitialized clock reference.

initialize scheduler after clock sources

---

crone/src/OscInterface.cpp
crone/src/SoftcutClient.h
lua/core/norns.lua
lua/core/softcut.lua
matron/src/event_types.h
matron/src/events.c
matron/src/oracle.c
matron/src/oracle.h
matron/src/weaver.c
matron/src/weaver.h

softcut voice now stores position per processing block, and i've added a query function to get the (accurate to block size) position of a voice.
i wanted to add this a different method to async check positions without throwing away a phase poll--- ie, being able to save a playback position "now" via a keypress
```
-- create simple print report callback
cb = function(idx,pos) print(idx,pos) end
-- arg is callback function
softcut.event_position(cb)
-- arg is which voice
softcut.query_position(1)
```
plumbing, wow.

softcut feature: query position

---

lua/core/metro.lua

realized that `metro.is_running` variable is dead/useless for non-infinite metros when someone tried to use it in a script. (actually a crow script which uses the same lua code, fwiw)
this change causes that state to be updated after firing a metro's event callback, if the stage count exceeds the metro's count. 
i think this is the behavior we want, but haven't actually tried it so not totally sure.
of course we could also just remove that field.

Fix metro running state

---

matron/src/clock.c
matron/src/clock.h
matron/src/clocks/clock_crow.c
matron/src/clocks/clock_scheduler.c

remove automatic sync events rescheduling logic in favor of explicitly rescheduling sync events to avoid the beat drifting away from hi-res sync-based counters.

clock sync chaining improvements

---

matron/src/clocks/clock_midi.c

this triggers clock transport start callback at zero beats/ticks (first realtime 0xf8 byte after 0xfa) making the behavior identical to internal clock.

start midi transport at zero ticks

---

lua/core/wifi.lua

two small changes:
- ensure the list of connections is up to date after `ADD` or `DEL`
- allow one connection profile to be used with different wifi interfaces

improve wifi ergonomics

---

lua/core/midi.lua

spun this up while working on a MIDI study, when I realized that it was a little wonky for authors to check whether a vport-stored MIDI device is _currently_ physically connected to norns. a niche gap, but one that's easy to fill :)
without this helper flag, connected state is only reflected by the presence of a `device` table in the MIDI vport's table or as a cross-reference to `midi.devices`. by piggybacking a `Midi.update_device_connected_state()` function to the end of `Midi.update_devices()`, the `midi.vports[x].device_connected` flag updates any time a MIDI device is connected or removed.

add 'connected' state to midi vports

---

matron/src/clocks/clock_scheduler.c
matron/src/event_types.h
matron/src/events.c
matron/src/weaver.c
matron/src/weaver.h

this PR changes the clock API to return current beat from `clock.sync` calls as follows:
```
clock.run(function()
local div = 1/4
for i=1,4 do
local beat = clock.sync(div)
local step = math.floor(beat / div)
print('beat', beat, 'get_beats', clock.get_beats(), 'step', step)
end
end)
```
so the above code would print
```
beat	0.25134		get_beats	0.25143		step	1
beat	0.50106		get_beats	0.50106		step	2
beat	0.75134		get_beats	0.75137		step	3
beat	1.00103		get_beats	1.00109		step	4
```
this basically allows tracking time in beat-synced coroutines without external counters and additional transport restart handlers, as current beat will be always returned from `clock.sync` and it will be naturally synced to the source transport too.
with this change `clock.sleep` calls will also return elapsed …

return beat from clock.sync

---

lua/core/menu/update.lua

the matron service now depends on jack, and shutting down jack now kills matron, so had to change the update process which was trying to shut down audio to save CPU during update

fix update process

---

lua/core/menu/params.lua

I have a little bug when using the `_menu.rebuild_params()` function:
In supertonic I use this to show/hide a bunch of track specific parameters. the function works perfectly well when I'm in a menu. but when I'm back in the main screen, if I use `_menu.rebuild_params()` then it will cause the screen to "flash" the menu quickly while it redraws and before it goes back to redrawing the main screen. I do want to rebuild the parameters, so that pressing K1 goes back into the parameters menu with the correctly shown/hidden parameters, but I don't want the menu to be redrawn. 
this pr fixes this - by checking if `_menu.mode` and then redrawing if so.

redraw menu when rebuilding only if in menu

---

matron/src/device/device_monitor.c

- check for crow using serial string on removal as well as addition
- don't process non-physical `/dev/input` entries (suppresses some error messages at startup)
- clean up debug prints
(i thought there were memleaks too, but apparently not)

device monitor fixes

---

matron/src/device/device_monitor.c

fixes broken midi from pr #1381. (by moving check for null device nodes to the specific add routine for `/dev/input`.)
there are still spurious and apparently benign errors when adding (some) HID devices. not going to worry about that right now, but it would be good to hunt those down, at least insofar as making sure the failed attempts aren't leaking memory.

Device monitor fixfix

---

lua/core/clock.lua
matron/src/clocks/clock_scheduler.c
matron/src/clocks/clock_scheduler.h
matron/src/weaver.c

this change enables various swing styles in coroutines using clock.sync by adding an optional `offset` parameter for `sync`, which can be used as follows:
```lua
clock.sync(1) -- sync and resume as usual
clock.sync(1, 0.5) -- sync and resume with a half-beat delay
clock.sync(4, -2) -- sync and resume 2 beats earlier
-- create a swinging feel for the whole script
local beat = 1/4
local groove = 0
while true do
local current_beat = clock.sync(beat, groove)
local current_step = math.floor(current_beat / beat)
if current_step % 2 == 0 then
groove = beat / 2
else
groove = 0
end
end
-- same as above, using XOR (~) for setting even/odd offset multiplier
local beat = 1/4
local offset = beat / 2
local swing = 0
while true do
clock.sync(beat, offset * swing)
swing = swing ~ 1
end
```

add offset (swing) parameter to clock.sync

---

sc/core/Crone.sc

reeeeal tiny fix to show the correct scsynth port number at boot. (just in case anyone is acting on this information, which is possible.)

post correct scsynth port on boot

---

lua/core/crow.lua

crow as a clock input source was broken because the clock C layer expects a magic string from crow (which was changed to a dynamic string with the crow namespace update).
this change forces crow to send the old-style event string so that it will match (without having to change the clock C layer to something more complex).

hotfix crow clock input handling with new crow namespace

---

lua/core/script.lua

We broke the crow initialization with the namespace update -- when a script is loaded it now calls `norns.crow.init()`.

script loads & calls norns.crow.init() instead of crow.init()

---

matron/src/clocks/clock_scheduler.c

this fixes broken syncs in coroutines, where clock.sleep is mixed with clock.sync as follows:
```
clock.run(function()
clock.sync(1)
clock.sleep(5)
clock.sync(1) -- broken, the coroutine will be resumed immediately
end)
```

fix clock syncing after sleep from the same coroutine

---

lua/core/config.lua
lua/core/hook.lua
lua/core/menu.lua
lua/core/menu/mods.lua
lua/core/menu/reset.lua
lua/core/menu/system.lua
lua/core/mods.lua
lua/core/norns.lua
lua/core/script.lua
lua/core/startup.lua
matron/src/weaver.c

this is a proof of concept which implements much of the functionality i proposed for #1384
this does not provide any ui or dynamic discovery of "mods". for demonstration purposes the `startup.lua` code was extended to look for `dust/data/mods.lua` and load that file at the end of matron's startup process. within `mods.lua` one can place code or call `require '<script_dir>/lib/<blah>'` to load files from the normal script/project area.

matron lifecycle hooks and system level mods.lua

---

lua/lib/util.lua

currently, if a script passes a smaller max than min to `util.wrap` or `util.wrap_max`, then norns will freeze. this PR adds an error print to maiden when the max is less than the min and avoids hangs

util.wrap and util.wrap_max: avoid min > max freezes

---

lua/core/crow.lua

Fix for https://github.com/monome/norns/issues/1402
`norns.crow.events` is a table of string keys, the `#` operator only works on tables of integer keys.

Use tab.count to get count of table w/ string keys

---

matron/src/args.c

Two changes here:
1) New `-h` option to print out the available options.
2) If an invalid option is provided matron will terminate with the default error message:
```
~$ ./matron -a
./matron: invalid option -- 'a'
```

Add -h option to matron.

---

matron/src/hardware/stat.c

Resolves segfault when a lines in `/proc/stat` is longer than 64 characters. This was happening regularly when running matron in a docker container.

Bigger buffer for long line in /proc/stat

---

lua/extn/sky/unstable/io/norns.lua

trivial addition to sky, allows the beat property to be explicitly set on redraw events which is useful when visualizing the current clock and also implementing transport start/stop behavior

sky: allow beat property to be set on redraw events

---

crone/src/BufDiskWorker.cpp
crone/src/BufDiskWorker.h
crone/src/OscInterface.cpp
crone/src/SoftcutClient.h
lua/core/softcut.lua
matron/src/oracle.c
matron/src/oracle.h
matron/src/weaver.c

Adds `mix_buffer_mono(file, start_src, start_dst, dur, preserve, mix, chan_src, chan_dst)` and `mix_buffer_stereo(file, start_src, start_dst, dur, preserve, mix)` methods to softcut. These methods act like `read_buffer`, except they mix the existing buffer content with the new soundfile according to the `preserve` and `mix` params. See #1151.
Questions:
- should there be a fade_time parameter?
- is `clamp(frSrc, bufFrames - 1);` towards the beginning of `BufDiskWorker::readBufferMono` a bug? It seems like this says that we can't read a position in a file past the length of the softcut buffer?
- I mildly refactored `BufDiskWorker::Job` to add a `mix` parameter before the callback. I hope this is okay.
- when I run `crone.sh` or `start.sh` on my Norns after building, I get `liblo error: …

Softcut NRT Enhancement: add preserve and mix to `read_buffer`

---

lua/core/keyboard.lua
lua/lib/textentry.lua
lua/lib/textentry_kbd.lua

this allows to use the keyboard in `textentry` menu (`TAPE`, Wi-Fi...).
please note that i had to create a new module `lib/textentry_kbd.lua` to hold the (temporary) callbacks. otherwise i would have had a circular dependency between `core/keyboard.lua` and `lib/textentry.lua`.
there might be a more elegant way to do this.

make keyboard work w/ textentry

---

lua/core/menu/tape.lua

when in textentry for tape name, and canceling (by hitting `K2` / `ESC` on keyboard):
- past behavior: a tape gets loaded anyway w/ a newly incremented `fileindex`, `K3` triggers record
- fixed behavior: tape doesn't get loaded, `K3` allows reentering the textentry for the tape name

don't load tape on cancel

---

lua/extn/sky/unstable/engine/polyperc.lua
lua/extn/sky/unstable/engine/polysub.lua

trivial change unstable sky engine wrappers, specifically
- do not add parameters when the device is constructed the first time
- add separator by default or optionally group into sub menu

sky: provide more control over polyperc/polysub parameter definition

---

lua/core/menu/params.lua

This PR makes PSET files list parsing more generic.
Before this PR, PSET list show only up to entry `#99`.
PSET entry `#100` could be saved but not loaded. Worse, it in fact overrode entry for PSET `#10`.

Support PSET entries above 99

---

matron/src/event_custom.h
matron/src/event_types.h
matron/src/events.c
matron/src/events.h
matron/src/matron.h
matron/src/weaver.c
matron/src/weaver.h
matron/wscript

this change opens up matron's event loop for access by c-based lua modules loaded at runtime.
the motivation for this change is to allow hardware devices such at the soundplane to have have the same direct, low overhead, channel for pushing events into the running script that built in matron devices enjoy. ...while avoiding the need to integrate/maintain the soundplane support directly in matron.
the approach is straightforward and modeled a bit after how the linux kernel achieves modularity. the new `event_custom` struct contains two pointers, one is an `ops` structure with functions pointers which the event loop core uses to handle the custom event behavior, the other is an arbitrary `value` pointer which gets passed back into the custom functions.
as a proof of concept (and to validate …

custom events

---

matron/src/hardware/stat.c

On machines with fewer than 4 cores the stat_check function ends up trying to process the "intr" line, which somehow ends up causing a crash. This fixes the crash by only processing lines beginning with "cpu".

Fix stat on machines with fewer than 4 cores.

---

matron/src/device/device_monitor.c

In some cases, `udev_device_get_property_value` can return a NULL. This causes a segmentation fault when trying to detect crow on some setups. Adding a check that the value isn't null fixes this.

fix crash when trying to detect crow

---

lua/core/paramset.lua

sometimes it would be nice to know the order in which parameters are recalled from a paramset. 
when adding params, we use `table.insert` with default position (last), so ordering is known at that point.
when actually reading the saved pset, we loop over lines in file, so that ordering is also known.
but in between, we loop using `pairs` to write the file... and while the order in saved .psets _looks_  consistent to me so far, lua spec explicitly says the order of `pairs` is undefined and cannot be relied on.
hence, this smallest imaginable change is i think enough to guarantee ordering. so why not

process parameters in order when writing pset

---

lua/core/startup.lua

this came up during the recent docker experimentation. i had incorrectly attributed it to a missing `dust` directory but it happens on any device which is free of mods.

handle no matching mods more gracefully

---

lua/core/menu/system.lua
watcher/src/main.c

- adds `SYSTEM > PASSWORD` which allows entry of new password for user `we` (does not require existing password, no confirmation, no display of current password)
- `watcher` now checks for `/boot.norns.txt`, if present resets pw to `sleep` and deletes `norns.txt` (this file can be created by mounting a norns in DISK mode via `rpiboot` or by inserting shield sdcard into computer) --- this is a failsafe in case the menu system won't load due to a broken update (or something)... the theory being that `watcher` is less fragile.
bonus (i guess): `SYSTEM` menu is now scrolling

watcher reset, menu passwd entry

---

matron/wscript
wscript

save `--desktop` option in environment so you don't need to type it at build

persist --desktop option between conf and build

---

lua/core/menu.lua
lua/core/menu/home.lua

'missing' errors don't give the user much in the way of next steps if they're new to the ecosystem -- even though troubleshooting is all well-documented and maiden has a heads-up built in, folks still ask how to resolve the error (spun this up after seeing a message posted to the study discord this morning).
this commit would add two bits of helper text, one on-screen and the other printed to the REPL.
**on-screen**, user would see:
```
error: missing ____
try 'SYSTEM > RESTART'
SELECT >
SYSTEM >
SLEEP >
```
**in REPL**, user would see:
```
loading engine: ____
```

verbose 'missing' message

---

lua/core/norns.lua

started doing this in `lua/lib/devtools.lua` but that `require()`d too much effort on the dev side. scanning all the files already included this felt like the most logical place. open to feedback!

add rerun()

---

lua/lib/musicutil.lua

This PR adds `generate_chord_roman` and `generate_chord_scale_degree` methods to `MusicUtil`, and a supporting data structure. 
`generate_chord_roman` is based on the equivalent method in the [WesternMusicElements](https://github.com/fredericcormier/WesternMusicElements) library that much of the rest of `musicutil` is drawn from. `generate_chord_scale_degree` is new, and any errors are mine.
A couple years ago I started an overly ambitious script that used roman notation heavily. (This project also drove #919.) It's still nowhere near finished, but some recent discussion of `musicutil` reminded me that this chunk of code existed and I thought it might be useful to someone.
Using `generate_chord_roman` you can access the same chord table as `generate_chord` via roman numeral notation, …

Add musicutil function for roman numeral chord generation

---

lua/core/clock.lua
matron/src/clock.c
matron/src/clocks/clock_link.c
matron/src/clocks/clock_link.h

The [Link test plan](https://github.com/Ableton/link/blob/master/TEST-PLAN.md) has two clauses about the expectations for how joining a session should affect the app/device tempo:
[TEMPO-2](https://github.com/Ableton/link/blob/master/TEST-PLAN.md#tempo-2-opening-an-app-with-link-enabled-should-not-change-the-tempo-of-an-existing-link-session): Opening an app with Link enabled should not change the tempo of an existing Link session.
[TEMPO-5](https://github.com/Ableton/link/blob/master/TEST-PLAN.md#tempo-5-enabling-link-does-not-change-apps-tempo-if-there-is-no-link-session-to-join): Enabling Link does not change app's tempo if there is no Link session to join.
So the behavior needs to be different based on whether the session has other participants or not. Luckily, this behavior is …

Joining an existing Link session should adopt the session tempo, not force the device tempo

---

lua/core/menu/update.lua

fixes #1472 by making a reasonable assumption: disk size when update starts should only be changed by the incoming download. so just show the diff. note that norns disk size query updates every 5 seconds (this is in the C layer) so this isn't super real-time, but it helps give some feedback and i think it's a big improvement.

add progress to update download

---

lua/core/grid.lua
matron/src/device/device_monome.c
matron/src/device/device_monome.h
matron/src/event_types.h
matron/src/events.c
matron/src/weaver.c
matron/src/weaver.h

Adds support for tilt.
Tested on norns shield and a grayscale 64 (2010-2012) - serial m64-0993  
grid presents as `grid monome 64 m64-0993 8x8`
For testing I added tilt to my grid-test script in this branch: https://github.com/okyeron/grid-test/tree/tilt
(tilt can be enabled/disabled in the params menu)
Results:	 
* X/Y data comes through, no Z (although no Z data was observed on Max test-grid patch either).
* Values displayed are between ~90 and ~170, with ~130 in the center (grid flat on table)
Questions:  
* Is there no Z on that grid model? Is there Z on others?
* What are expected values? Seems like 0 to <200 when testing with the Max test-grid patch

Add Tilt support for legacy grids

---

crone/src/crone_main.h
crone/src/main.cpp
crone/wscript
matron/src/main.cc
matron/src/matron_main.h
norns/main.cpp
norns/wscript
wscript

combine processes, as described in PR #1479 
- add new target `norns/wscript`, combining sources from `matron/src` and `crone/src`, producing executable at `build/norns/norns`
- small necessary edits to component `main` sources / routines; otherwise sources are unmoved/unchanged
seems to mostly work, with a big caveat: connection to sclang is pretty well broken since the order of process dependencies no longer applies and it is not possible to launch `sclang` between `crone` and `matron`.
fixing this will require some changes to sclang classes (which will be subject of a future PR to v3) and of course to systemd service definitions (which are not in this repo.)

consolidate crone/matron processes

---

crone/src/MixerClient.cpp
crone/src/main.cpp
matron/src/matron_main.h
norns/main.cpp
sc/core/Crone.sc

encountered a _fascinating_ performance issue:
- seems that posix `system()` and `popen()` routines perform a full fork of the parent process. this involves copying all thread states (?) including RT/audio threads, which apparently also requires halting the threads in question.
- both the C and lua layers of `matron` perform a lot of child process calls. after combining `matron` and `crone` processes, every one of these calls would halt the audio threads and cause underruns.
seems a little crazy, but seems to work: 
- fork the parent process immediately into 2 child processes, before any threads are created
- now when the `matron` process forks, only its own threads are affected; other child process is fine.
(NB: it didn't seem to be entirely effective to keep `crone` routines in the …

V3 wip/fix combined process

---

lua/core/menu/select.lua

`alt` variable was not enclosed in the `m` table, which causes namespace collision with scripts which have `alt` in the script's scope.

fix alt variable

---

crone/src/Commands.cpp
crone/src/MixerClient.cpp
lua/core/menu/params.lua
lua/core/menu/reset.lua
lua/core/menu/system.lua
lua/core/menu/tape.lua
lua/core/menu/update.lua
lua/core/norns.lua
lua/core/script.lua
lua/core/startup.lua
lua/core/wifi.lua
lua/lib/util.lua
matron/src/weaver.cc

added new FFI function `_norns.execute` that calls `sidecar_client_cmd` and returns directly to lua.
replaced all calls to `os.execute` and `io.popen` in lua `core/` and `lib/`
so far, seems to have fixed all remaining xruns for me.

V3 wip/replace lua calls

---

matron/src/hardware/screen.c

compiles, but untested. fixes https://github.com/monome/norns/issues/1491

save/restore for png-display

---

crone/src/Commands.h
crone/src/MixerClient.h
crone/src/crone.h
crone/src/crone_param_dispatch.cpp
crone/src/crone_param_dispatch.h
crone/src/main.cpp
matron/src/oracle.cc
norns/wscript

mostly complete replacement of OSC->crone with direct calls in `oracle.cc`
one tricky point concerns the use of parameter strings from lua. these are used in generic sofcut and FX param setters simply to avoid LOC in glue modules.  this made more sense with OSC as endpoint (matches on strings anyway). now it feels a little sillier, but for now instead of adding lots of LOC, added a dispatch module mapping `std::string` to setter funcs. have not completed this for FX params, only softcut params.
compiles but still quite untested. opening PR early for visibility.

V3 wip/replace osc hack

---

matron/src/event_types.h

this change is to address the ABI breakage which was introduced as part of the addition of grid tilt support. the EVENT_GRID_TILT entry was moved to the end of the enum definition and a comment was added which states that new event types must be added to the end of the list.

move EVENT_GRID_TILT to the end of event_t enum

---

lua/core/paramset.lua

from https://llllllll.co/t/bounds/23336/68, the params system doesn't currently protect against ID collision, which can lead to unintentional overwrites. this implementation simply prints the error to matron, same as the other `paramset.add()` errors -- it seemed best to stick with this pattern, unless we want to actually force a load error?
i tested this approach with `bounds`, which positively surfaced the error and avoided the collision by not adding the script's `input_level` re-definition. also tested with scripts that have a lot of params and didn't see any noticeable load time lag with this iterative approach, but am totally interested/open to optimization of this rather brute-force approach!

avoid adding duplicate/colliding param IDs

---

readme.md

1. Links to tagged github users: if the developers are being credited, I figured linking to their github user accounts is even better! Ideally this should happen automatically within the GitHub world, but the tags weren't becoming hyperlinks by default :(
2. Updates tagged names of github users that have been changed—I discovered they had been changed from viewing the documentation at the [monome norns site](https://monome.org/docs/norns/)
3. Creates sections for content to break up text, making documentation easier to scan and comprehend.
4. Adds information describing norns to quicken understanding and introduction to newcomers.
5. Changes github link text to nouns instead of the urls to lessen cluter created by full url strings
As I was passing through this repo on my quest to learn …

Attempts to improve readability of README

---

crone/osc-methods.txt
crone/src/Commands.h
crone/src/OscInterface.cpp
crone/src/SoftcutClient.cpp
lua/core/softcut.lua

please see this PR: https://github.com/monome/softcut-lib/pull/59

stop after next loop+fade 

---

lua/core/clock.lua

Previously, it would either rise on the division and fall halfway
between the divisions or vice versa, and which one would be based on
the vagueries of timing.

Make crow clock out always rise on the given division.

---

matron/src/weaver.c

two small changes:
- erroneous cast to `float` and back in softcut `_ii` parameter setter. looks like a copy/paste or codegen error. i am pretty sure this was benign.
- in weaver `_set_cut_param_iif`, indices **were not being converted from 1-base to 0-base**. this would cause a pretty serious bug. fortunately it was as un-serious as could be expected, since it only actually affects the `voice_sync` command which i believe is pretty rarely used. (i wonder if there are any scripts using it actually.)
(note that several other commands that are handled by `SoftcutClient` also accept `iif` parameters; but these are all "levels" and are processed through a different `weaver` function.)

fix softcut param types and _iif base

---

readme-setup.md

- some required packages were missing (`jack-dev`, `libboost-dev`)
(yes yes, we should remove boost dependency.)
- general description of system components was very old (particularly bits about supercollider)
- included some pointers on how to run individual components during development

update readme-setup with packages, component descriptions

---

crone/osc-methods.txt
crone/src/Commands.h
crone/src/OscInterface.cpp
crone/src/SoftcutClient.cpp
lua/core/softcut.lua

Reverts monome/norns#1494
@schollz i apologize--- i misunderstood some of the technical issues with this PR (i misinterpreted the problem as pre-existing), and without a clean fix i'd prefer not to add technical debt to the project. i understand your soft-fix of pushing the play command later generally "works" but we'd need a robust fix prior to adding this feature to main.
furthermore there are some needed optimizations, as i learn more about the careful architecting done by @catfact in the dsp loop.
i'm reverting this PR as an overdue norns update is waiting, and i can't foresee a realistic timeline for fixing this issue.

Revert "stop after next loop+fade "

---

lua/core/paramset.lua

reverting this error to a warning. 
i believe it should ultimately be an error, but that's not ideal for the moment without an extended beta period. i'm not quite convinced its doing what we want as i'm seeing some seemingly spurious/inconsistent examples that should be examined more thoroughly.
one obvious difficulty is that script params may collide with mod params! oy.
in any case, this change should make things better than before the error, because it adds an early return to the function instead of clobbering an existing param in the lookup table
...actually now that i think about it i'm not sure this is "better." scripts will still be broken because they have non-functional parameters. but they will not "steal" parameters from the system, breaking stuff even after the script is …

make param ID collision a scary warning instead

---

lua/core/menu/tape.lua

This looks directly to the contents of `tape/` to figure out what the index is, which _should_ be more reliable than looking at `index.txt`. I was having an issue where appending to the filename of stuff I'd recorded (e.g. `0012 - mlr - c minor`) prevented `index.txt` from incrementing.
It didn't seem possible to make this a mod, but if I'm missing something I'm happy to go that route instead.

get tape index from file system, not index.txt

---

readme-setup.md

so, i forgot that we actually removed all boost usage from crone/softcut already
but i guess failed to remove the requirement from `wscript`/readme, so this change does that.
the only thing that gives me pause is the references to boost in the `link` sources. but AFAICT it seems to work.

remove unneeded (?) boost requirement

---

lua/core/screen.lua
matron/src/hardware/screen.c
matron/src/hardware/screen.h
matron/src/weaver.c

adds the ability to direct screen drawing to an image
the api is straightforward:
```lua
image = screen.create_image(32, 32)
screen.draw_to(image, function()
local w, h = image:extents()
screen.clear()
screen.level(15)
screen.aa(0)
screen.rect(0, 0, w, h)
screen.stroke()
screen.update()
end)
```
under the hood a screen "context" (aka cairo_t) is allocated and attached to the image object when drawing to the image is first attempted. this is done lazily for simplicity of user experience and to avoid allocating additional data for images which are never draw to. during the execution of the `screen.draw_to(...)` function the cairo context associated with the screen swapped out for the context associated with the image, the contexts are independent so any changes made to settings like `aa` or …

screen: draw to image support

---

crone/wscript
matron/wscript

- changed `crone` opt level to `O3` and added a couple more flags on top for release builds. this squeezes another 2-3% of audio load headroom according to `baseline`. (not dramatic since we already had auto-vec stuff enabled at O2.)
- also propagated the CPU and FPU selections to `matron` for release builds. so that is probably a little faster too but we dont have as convenient a profiling mechanism.
the minor downside is that a few seconds have been added to compiation time.

More opt flags

---

doc/modules/paramset.html
lua/core/menu/params.lua
lua/core/paramset.lua

while writing up examples for saving table data with PSETs (building off of @schollz 's incredible work on this front), i realized that PSET index number is a helpful reporting callback -- since PSETs made via the PSET UI can share names, the index number is often the only differentiator. rather than force authors to extract this from the loaded filename, it made sense to add the PSET's index number (if available) to the actions.
i also realized that a PSET deletion action would be helpful for external data management, so i added that as well.
here's a quick example of usage:
```lua
MusicUtil = require 'musicutil' -- see https://monome.org/docs/norns/reference/lib/musicutil
s = require 'sequins' -- see https://monome.org/docs/norns/reference/lib/sequins
base_note = …
```

add PSET number to PSET actions + add delete action

---

.gitmodules
lua/core/script.lua
lua/core/startup.lua
matron/src/weaver.cc
norns/wscript
third-party/wscript
wscript

this replaces #1543, rebased on the `norns-converged` branch and updated for the switch to using a c++ compiler.

matron: embed lua-cjson module as `json` global

---

norns/main.cpp

performs a single fork for the sidecar process along with:
- set the child process name for visibiliy in ps
- set the thread name in child process for visibility in gdb
- send child a SIGHUP if parent dies
- disconnect child from parent stdin
the primary motivation for this change is simplicity and
to allow easier debugging. the parent process remains the
one running crone/matron.
with this modification the output of `ps` looks something like:
```
...
we         618     1  0 22:23 ?        00:00:00 /home/we/norns/build/ws-wrapper/ws-wrapper ws://*:5555 /home/we/norns/build/norns/norns
we         619   618 15 22:23 ?        00:00:07 /home/we/norns/build/norns/norns
we         623   619  0 22:23 ?        00:00:00 sidecar [norns]
...
```

norns: only fork sidecar

---

lua/core/softcut.lua

small fix for a small issue.
softcut lua parameter factory method creates a param to control `post_filter_fc_mod`, which doesn't exist because only the pre-filter has rate-coupled modulation.
this is presently causing scripts that just add the entire param factory output to print `warning: didn't find SoftCut voice method: post_filter_fc_mod`. (no other ill effects that i know of, except efficiency i guess.)

remove nonexistent post_filter_fc_mod command from softcut param factory

---

maiden-repl/src/io.c
maiden-repl/src/pages.c
maiden-repl/src/pages.h
maiden-repl/src/ui.c
maiden-repl/src/ui.h
maiden-repl/wscript
norns/sidecar.cpp
norns/wscript
ws-wrapper/src/main.c
ws-wrapper/wscript
wscript

the `nanomsg` library is in maintenance mode and has been superseded by  `nng`. additionally `nng` supports secure websockets which will be required in order to (eventually) add authentication to maiden.
_in order to build with this change the `libnng-dev` package must be installed._ 
while `nng` does offer compatibility headers for `nanomsg` the sidecar, maiden-repl, and ws-wrapper code has been updated to use current `nng` api in order to maintain consistency once authentication is implemented.
some minor touchups to maiden-repl are included as well (build cleanup and one crash fix)

replace nanomsg with nng

---

lua/core/audio.lua
lua/core/hook.lua
lua/core/script.lua
lua/core/startup.lua
matron/src/jack_client.cpp
matron/src/jack_client.h
matron/src/weaver.cc

- adds low level wrappers for various `jack` functions to introspect and manipulate ports
- adds high level api to alter audio routing by port, by tables of ports, or by component
- adds a hook for tweaking audio routing in mods
- ensures supercollider is connected on restart
- removes all system calls out to `jack_*` commands

provide the ability to manipulate audio routing

---

matron/src/weaver.cc

corrects a bad typo which must have been introduced when cleaning up the PR originally

fix registration for screen_display_image_region

---

lua/core/norns.lua
matron/src/clocks/clock_internal.cc
matron/src/clocks/clock_link.cc
matron/src/clocks/clock_scheduler.cc
matron/src/device/device.cc
matron/src/device/device_monitor.cc
matron/src/event_types.h
matron/src/events.cc
matron/src/hardware/battery.cc
matron/src/hardware/input.cc
matron/src/hardware/stat.cc
matron/src/input.cc
matron/src/metro.cc
matron/src/system_cmd.cc
matron/src/system_cmd.h
matron/src/weaver.cc
matron/src/weaver.h
norns/sidecar.cpp
norns/sidecar.h

- fix capture buffer termination (issue #1569)
- moves async command capture logic from lua to c
- ensures sidecar requests from `_norns.execute` and `_norns.system_cmd`
are not interleaved when called from different threads
- adds progressive capture buffer allocation in server up to
maximum of 10MB
additionally this change adds a sidecar client side "request queue" which is derived from the core event queue. while overkill for this particular fix the intension is to lay part of the infrastructure for moving the `stat.cc` logic out of the main norns process and into the sidecar which will reduce the overhead of gathering stats.

sidecar: serialize command invocation requests

---

lua/core/paramset.lua

currently, param separators don't get registered to the lookup table, so there's no way to use `params:show` and `params:hide` -- rather, the user needs to do a bit of sleuthing to find the params ID and then directly change the `params.hidden` table.
i just added lookup registration if the separator is named, and then added a dummy name for unnamed separators -- lemme know if this is too much scaffolding and we can just document that a separator needs to be named in order to have its visibility changed with `:show` and `:hide`
i also adjusted `params:visible` so it could be queried with string or index, as `:hide` and `:show` are.
please lemme know if anything is missing!
test script:
```lua
params:add_separator("visibility test")
end
function key(n,z)
if n == 3 and z == …
```

add param separators to lookup table

---

lua/core/params/group.lua
lua/core/params/separator.lua
lua/core/paramset.lua

while scripting tonight, i realized https://github.com/monome/norns/pull/1539 did not anticipate situations where an author might do the following:
```lua
params:add_number('my var', 'my var', 1, 127)
[...]
params:add_separator('my var')
```
though it's convention to use underscores within parameter ID's, the system supports ID instantiation with spaces, so there's a chance someone will accidentally clobber their useful parameter with a separator or group name. since separators and groups do not have ID's, only names, this seems like a good guardrail.

params: align 'add_separator' and 'add_group' flow with other paramtypes

---

lua/lib/lattice.lua

Without this change, a swing of 66 will shift some events early and some events late from where they would otherwise be. With this change, a swing of 66 leaves some beats alone, and shifts other beats late from where they would otherwise be. 
Example to evaluate change, run as a norns script:
```
engine.name = "PolyPerc"
local lattice = require("lattice")
l = lattice:new()
p1 = l:new_pattern{
enabled = true,
division = 1/4,
action = function(t)
print("q", t)
engine.hz(440) 
end,
}
p2 = l:new_pattern{
enabled = true,
division = 1/8,
swing = 66,
action = function(t)
print("e", t)
engine.hz(660)
end,
}
l:start()
end
```
In this example, the expected behavior is that two events (440 and 660) fall on the "down" beat, and then one (660) falls on the "up" beat, but with a …

Place downbeats correctly.

---

lua/core/midi.lua

Revert "fix to add midi data when device is removed (issue #1557) "

---

lua/core/midi.lua

this executes the global, customizable midi device removal callback when a device is unplugged (if the device is registered by the norns midi system), in addition to and without affecting the per-device removal callback (if defined.)
alternative to PR #1562, addressing issue #1557

execute global Midi.remove callback

---

lua/lib/lfo.lua

gah! the `:add` method wasn't properly invoking the `.new` function. corrected (+ fully tested) with this PR.
very very sorry for missing this in prior testing!!

hotfix: lfo `:add`

---

lua/core/paramset.lua

tonight, i realized that adding separators to the lookup table in #1584 means they get collected by the PSET writer. this is generally fine, since they don't have a `:set` action, but this syntax situation would result in an error if a PSET were saved and subsequently loaded for a script with conflicting parameter IDs:
```lua
params:add_number('velocity', 'velocity', 0, 127)
-- [...] some other params [...]
-- assuming another section of the params wanted to use 'velocity' to demarcate a set of actions,
--   but the author didn't provide a unique ID:  
params:add_separator('velocity') 
end
```
the resulting PSET file would look like:
```bash
-- my_PSET
[...] SYSTEM PARAMS [...]
"velocity": 43
[...] some other params [...]
"velocity": 
```
and the PSET read would attempt to …

do not add separators to PSET file (and avoid historical collisions)

---

lua/core/screen.lua

The documentation for screen.curve and screen.curve_rel seems to have the parameters the wrong way round - the last pair are the desination. Documentation is auto-generated from the code isn't it? Ignore me if I'm talking non-sense :)

fixed screen curve param descriptions

---

lua/lib/fileselect.lua

This would close #1581
The operation is basically as proposed: E3 will turn on and off previewing, which hijacks TAPE.
Currently it's very bare-bones; so for instance if TAPE is muted, no sound will be heard.
Thoughts / suggestions / comments welcome :)

add TAPE previewing to fileselect

---

lua/core/keyboard.lua
lua/core/menu.lua
lua/core/osc.lua

These are some keyboard tweaks I mentioned in https://github.com/monome/norns/discussions/1610
I created each as a individual commit if you'd like to cherry-pick ones to include.
Here is a virtual norns where they can be tested: https://play.norns.online/.
The main changes are: 
- F1-4 go straight to menu screens.
- F5 toggles on/off menu
- holding a key continues to adjust
- +/- keys adjust parameters
- osc handler can transmit keyboard (in the virtual norns the browser is sending keystrokes via osc)

Tweaks to the keyboard

---

lua/core/menu.lua
lua/core/menu/home.lua
lua/core/norns.lua
lua/core/script.lua
lua/lib/fileselect.lua

Adds an error on script load if the script writer sets the value of `norns.version.required` to a number (or string) representing a date newer than `norns.version.update`. This variable should be set outside of `init`, since the check happens before even the `pre_init` hook is called.

add version error

---

lua/core/clock.lua

addresses issue #1612
adds a call to the script-defined `clock.tempo_change_handler` function whenever the `clock_tempo` parameter is changed in the parameters from an external source. tested with the snippet included in the issue.

send external source tempo to clock.tempo_change_handler

---

lua/lib/lattice.lua

In talking with @tyleretters, we felt it would be good to move away from "pattern,"
which implies maybe a bit more structure than something like "sprocket".
A sprocket performs a simple function repeatedly;
more whimsical than "cam" or "cog," which are maybe more accurate.
Added an optional "priority" parameter for sprocket creation.
There are 5 levels of priority, with 1 being the highest.
All higher priority sprockets will be triggered in order of creation before lower priority sprockets trigger.
The inclusion of "meter" seems to add needless complication;
for example I noticed the docs are not correct.
Musically, a "quarter note" is the same speed regardless of whether the meter is divided in four or in five,
but changing the meter parameter on Lattice resulted in different meanings of …

work on lattice v2

---

lua/core/menu.lua

a (sub-)menu can register `_menu.keycode` and `_menu.keychar` callbacks.
before this fix, `_menu.keychar` would never get called.
i discovered it while doing a user interface for a mod (which doesn't rely on the `script` i/o API but the `menu` one).

fix `_menu.keychar` not getting called

---

lua/core/menu.lua

**before:** if a sub-menu defines its own `_menu.keycode` callback, it gets evaluated **in addition and after** all the **default global keycode mappings**.
these default mappings are nice for most menus but can prevent making custom specialized interactions for sub-menus that have a slightly different logic (mod screens, typically).
**after:** if a sub-menu defines its own `_menu.keycode`, it **takes precedence** over all of the default menu mappings (except the `F1`..`F4` shortcuts).
**only small drawback**: if this sub-menu wants to use some of the default mappings for itself, it needs to redefine them in its own `_menu.keycode` callback.

proposal: prevent global menu shortcut messing up w/ sub-menu's

---

lua/core/startup.lua

i discovered that https://github.com/monome/norns/pull/1439 introduced this error when `script.clear` gets called.
```
/home/we/norns/lua/core/script.lua:90: attempt to call a nil value (field 'clear')
stack traceback:
/home/we/norns/lua/core/script.lua:90: in function 'core/script.clear'
/home/we/norns/lua/core/script.lua:166: in function 'core/script.load'
(...tail calls...)
```
[corresponding line](https://github.com/monome/norns/blob/487610b28b7d5a876c5df7f58890d58ed3b31605/lua/core/script.lua#L90):
```lua
keyboard.clear()
gamepad.clear()             -- <- culprit
```
the problem was that unlike `keyboard`, `gamepad` was not loaded in the global context.

fix undefined `gamepad` when `script.clear` gets called

---

lua/core/menu/system.lua

WPA-PSK requires a sequence between 8 and 63 ASCII characters, so if a user uses this prompt to change their password to something shorter, then they won't be able to access hotspot (due to the conveniences added by https://github.com/monome/norns/pull/1570).
to help guardrail, this commit adds:
- an on-screen `textentry` check which shows a countdown to 8 characters and a warning if the password goes beyond 63
- a character count check to `m.passdone`, which will only change all passwords if the string length is >= 8 and < 64, otherwise it prints warnings to maiden that the password has not been changed
(built after a super helpful troubleshooting support ticket from raja!)

add password length failsafes for WPA-PSK

---

lua/lib/lfo.lua

fixed locally global variables for `scaled_min` / `scaled_max`, `mid`, and `rand_value`, which interfered with scaling when multiple LFOs were running with different min/max values and baselines. [reported via `@WilliamHazard` here](https://llllllll.co/t/lfo-lib/60274/2). edit: [tested + confirmed workling](https://llllllll.co/t/lfo-lib/60274/9) both on my side + for spencer's case!
also, added `mid: rising` and `mid: falling` as options for the `reset_target`, which allows more musical control over how the reset affects the starting value. these options are placed at the end of the option table, so PSETs are not interrupted.

lfo fixes + improvements

---

lua/core/clock.lua
lua/core/midi.lua
lua/core/state.lua

Added an option to the "midi clock" param under `clock.lua`, "all", which sends clock to every device whose name isn't "none".

allow sending midi clock to all devices simultaneously

---

lua/lib/lattice.lua

Here's the corresponding issue: #1637
Lattice transport values should be increased outside the for-loop. 
In the current state, the transport values are increased in steps of 5, due to the sprocket ordering logic.

fix lattice transport value getting increased in steps of 5

---

maiden-repl/CMakeLists.txt
maiden-repl/README.md

I've updated the cmake build settings to work with latest macOS (and homebrew paths).

Make maiden-repl compile on macOS 13.1 Ventura

---

lua/core/arc.lua
lua/core/grid.lua
lua/core/hid.lua
lua/core/midi.lua

related to https://github.com/monome/norns/pull/1643, i noticed that script-defined grid, arc, MIDI and HID add/remove callbacks were persisting past script life.
<details>
<summary>test scripts</summary>
```lua
-- all the device add/remove callbacks!
-- each persists into a new script load
function midi.add(dev)
print('custom midi add callback!')
end
function midi.remove(dev)
print('custom midi remove callback!')
end
function grid.add(dev)
print('custom grid add callback!')
end
function grid.remove(dev)
print('custom grid remove callback!')
end
function arc.add(dev)
print('custom arc add callback!')
end
function arc.remove(dev)
print('custom arc remove callback!')
end
function hid.add(dev)
print('custom HID add callback!')
end
function hid.remove(dev)
print('custom HID remove callback!') …
```

clean up device callbacks

---

lua/core/clock.lua

`_menu.rebuild_params()` gets called elsewhere throughout the stack (including MIDI device add/remove), which makes this unnecessary -- it also seems to cause race-condition conflicts as the rebuild attempts to index parameters which don't yet exist

remove unnecessary _menu.rebuild_params() from clock.lua

---

lua/core/keyboard.lua

This fixes a problem in which a (typing) keyboard can generate an unrecognised code, resulting in a Lua error in the norns libraries, and possibly in a user script, too.
I recently reported - wrongly - an error with the zxcvbn script. You can [see the details here](https://github.com/schollz/zxcvbn/issues/25). The core of the problem is that I have a keyboard which generates errors when some function keys are pressed, as seen here in maiden:
```
lua: 
/home/we/norns/lua/core/keyboard.lua:132: table index is nil
stack traceback:
/home/we/norns/lua/core/keyboard.lua:132: in function 'core/keyboard.process'
/home/we/norns/lua/core/hid.lua:177: in function </home/we/norns/lua/core/hid.lua:162>
```
This is because when some keys are pressed they generate unlisted …

Remove error from unknown key press

---

lua/core/screen.lua

Not knowing this foxed me for a good couple of hours, so adding it here to help others.
The source of this info is in the Cairo documentation for its [fill](https://www.cairographics.org/manual/cairo-cairo-t.html#cairo-fill) and [stroke](https://www.cairographics.org/manual/cairo-cairo-t.html#cairo-stroke) calls.

Update docs for screen.fill() and screen.stroke()

---

lua/core/audio.lua
lua/core/clock.lua

very minor. aligns separator ID naming and gets rid of a straggling unnamed separator (which renders as 'separator' in the UI)

better separator labeling in core params

---

lua/core/clock.lua

during release testing, i realized that after my ~40th script load, `clock.sync` calls were off by a tenth of a beat, compounding as i continued to load scripts.
i started rolling back through commits and when i verified that b932b0d sparked the issue's emergence, i realized that the `send_midi_clock` table was being added to each time `clock.add_params()` was called, but never emptied out. so, eventually, the clock was doing 24ppqn calls on a table with *tons* of entries.
i guess nice to accidentally stress-test that a lot of devices could receive MIDI clock before timing issues emerged? anyway, fixed now!

refresh 'send_midi_clock' table with 'clock:add_params()'

---

lua/core/keyboard.lua

As discussed in #1657, enable developers to work with printable characters from within `keyboard.code()`, plus supporting documentation.
- Includes new function `keyboard.code_to_char()`. 
- Includes a new function `keyboard.char_to_code()`.
- Replaced some code from `keyboard.process()`, to use `code_to_char()` - which just uses that original code.
I suggest further discussion on this topic takes place here, not in the originating issue.
This PR does not include updates to the `docs/` directory because when I generated the docs it made too many changes (most notably updating every external reference in the docs to the Lua 5.3 manual). I presume the docs will be generated before an official release. However, I have tested locally using `ldoc`.
This PR does not include the suggested …

Implement character/key conversion

---

lua/core/screen.lua
matron/src/hardware/screen.c

fixes #1548
- scales pixels by 4, adds 64 pixel black border
- adds `screen.export_png(file)` to `dust/data/(script)/(file).png`
concerns
- gamma is off. previously using imagemagick `-gamma 1.25`

improved png export

---

lua/core/norns.lua

`norns.` helper to avoid [all of these steps](https://monome.org/docs/norns/help/#expanding-storage) after fresh installing.
if 4gb cm3 is installed, expand does not occur and prints a message to matron.

norns.expand_filesystem()

---

lua/core/gamepad_model/index.lua

so rn only 2 gamepad models are suported natively (profile bundled w/ norns core).
i made a [small norns script](https://github.com/p3r7/gamepad_wiz) that allows one to generate profile from a pluggued in gamepad and output it under `~/we/dust/data/gamepads/`.
this PR enables sourcing those user-level profiles dynamically.
2 qs:
- is this a sane approach?
- what about the name / location of the user's gamepad profile (`~/we/dust/data/gamepads/`)?

allow user to add gamepad profiles without tempering w/ core

---

lua/core/menu/settings.lua

fixes #1674
`SETTINGS` has two groups of entries -- `list` (`{"RESET", "PASSWORD >", "BATTERY WARNING"}`) and `pages` (`{"RESET", "PASSWORD"}`).
since `enc` turns increment `m.pos` by the number of `list` entries, hitting K3 on `BATTERY WARNING` tries to index `pages` with a non-existent entry. this fix specifies that K3 should only have an affect if `"RESET"` or `"PASSWORD"` are selected.

fix: K3 on BATTERY WARNING

---

lua/core/screen.lua
matron/src/hardware/screen.c
matron/src/hardware/screen.h
matron/src/weaver.c

reverts #1669 
resized/bordered export function now called `export_screenshot`

revert export_png and rename export_screenshot

---

lua/lib/fileselect.lua

addresses #652, an oldie but a goodie!
in this PR, `fileselect.enter` ends with an optional `filter_string` argument, which gets stored in `fileselect.filter` and allows UI filtering at a scripting level. if a script doesn't provide a `filter_string`, then `"all"` is used by default, surfacing all filetypes in the UI as expected.
filter strings can either be `"all"` (the default if `nil`), `"audio"` (just piggybacks off `fileselect.lua`'s existent playback length calculation function), or a specified file extension (eg. `".wav"` or `".pmap"`). the latter supports totally arbitrary extensions, which can be useful for scripts which create their own files (eg. cheat codes uses `.cc2` to save/load configs).
here's a to-the-point test script: …

add filters to fileselect

---

lua/core/clock.lua

fixes #1679 by adding a check to see if `send_midi_clock` already contains the initiated device, which avoids the double-registration which gets triggered by `params:default()`

hotfix: midi clock double-up

---

lua/lib/fileselect.lua

ah! i had totally spaced on the auto-shortening of long filenames by appending '...', which confused the "is this a file or is this a folder?" mechanism! #1681 is now fixed + and i will ask for community testing!

fileselect: handle '...' display names

---

matron/src/event_types.h

Closes #1689 
The integer representing the disk size is getting truncated.
Uncommenting [the `fprintf` in `matron/src/hardware/stat.c`](https://github.com/monome/norns/blob/c5adf1cb64184c48c429c7b6c9fb9e90f2833d86/matron/src/hardware/stat.c#L74) shows the correct disk size in `/var/log/daemon.log`. 
This value is [assigned to the `ev->stat.disk` field](https://github.com/monome/norns/blob/c5adf1cb64184c48c429c7b6c9fb9e90f2833d86/matron/src/hardware/stat.c#L133), which is only [a `uint16_t`](https://github.com/monome/norns/blob/c5adf1cb64184c48c429c7b6c9fb9e90f2833d86/matron/src/event_types.h#L241).
However, in `weaver.c`, the `disk` value is [expected to be a `uint32_t`](https://github.com/monome/norns/blob/c5adf1cb64184c48c429c7b6c9fb9e90f2833d86/matron/src/weaver.c#L2373).
This fix …

Ensure that disk field can represent size of larger sd cards

---

lua/core/softcut.lua

softcut's `voice_sync` command has its arguments reversed in the API docs.
[current documentation](https://monome.org/docs/norns/api/modules/softcut.html#voice_sync): `voice_sync (src, dst, offset)`
[source](https://github.com/monome/softcut-lib/blob/57fb9877e13b991aa642246ced70e7fff00c5b1b/softcut-lib/include/softcut/Softcut.h#L176-L178): `syncVoice(int follow, int lead, float offset)`
(@tehn , this'll need a docs re-gen!)

small fixes: softcut API

---

lua/core/menu/params.lua
lua/core/params/control.lua
lua/core/params/number.lua
lua/core/params/option.lua
lua/core/paramset.lua
lua/core/pmap.lua

on the way to addressing #1649, i realized i could also add an 'echo' mode which sends a map of the parameter value back to the mapped controller -- this is useful for MIDI Fighter Twister, OP-Z, and select Faderfox units which have addressable LEDs.
so now, any MIDI-mapped parameter now updates the corresponding `norns.pmap.data[id].value` whenever `:set` or `:delta`'d, so that MIDI devices don't get out of sync if a parameter is changed on norns (either by scripting or physical interaction).
there's also now an `echo` option in the mapping menu, which sends the lo/hi-scaled `norns.pmap.data[id].value` back to the controller, to redraw LEDs and/or display current values.
i've tapped into the existing `params:set` and `params:delta` framework to get this done, which seems performant from …

midi mapping touchups + extensions

---

lua/core/gamepad_model/index.lua
lua/core/gamepad_model/retro_controller.lua

thanks to the help of @xmacex i discovered a bug in the user-level gamepad model lookup (under `~/we/dust/data/gamepads/`).
also this PR adds support for a new gamepad model.

fix user gamepad profile lookup + new model

---

matron/src/system_cmd.c

this simply doubles the size of the temp buffer used for shell command results, from 64kB to 128kB.
it's painful to look at this! it would be nice to make something more incremental.
e.g., it would be nice to make better use of POSIX dirent iterators (? or whatever) to make dedicated   C implementations for tasks like listing all files of a given type in a directory.
if that's too much, maybe we can just change this to use `realloc` incrementally at least. i'll update here if i get a chance, but the change as is should at least support current use cases and i don't think the extra temp allocation will break anything.

double the temp buffer size for systemcmd

---

lua/core/menu/select.lua

* Do not scan through .git directories while looking for scripts (optimization of `find` call only).
* Filter out unwanted lua scripts before returning from shell.
This PR is a refinement of the tweaks to the `find` call that have already been merged (i.e., use of `-printf "%P\n"`).
Based on anecdotal tests on my local install, moving the filter for "crow", "lib" and so on from lua to `grep` removes 90% of the data transferred from the system call to crone.  This removes all lag on entering the select menu.  (Tested with an install base of 87 scripts having 555 unwanted internal lua files.)

Trim away un-needed select menu content

---

lua/lib/lfo.lua

following up from this https://github.com/monome/norns/discussions/1687 discussion, here's a PR that:
- changes the behaviour of the `offset` parameter and sets its `min` / `max` values according to the `baseline` value.
- adresses a bug where the lfo would not run smoothly when set to free and norns clocked via midi. the clock jitter would lead to constantly changing `clock.get_beat_sec()` values, which is required for the phase calculation and hence led to erratic changes.
- added the missing `lfo_phase_` param to `lfo_params_visibility()`.
let me know if there are any changes required.
best
s

changed offset behaviour + bugfixes

---

matron/src/hardware/cpu_time.c
matron/src/hardware/cpu_time.h
matron/src/system_cmd.c
matron/src/weaver.c
matron/wscript

adds a very simple module for measuring CPU time deltas accurately from lua. this is useful for benchmarking.
e.g.:
```
local perform_bench = function(nruns, nsteps, fn_step, fn_init)
local times_ms = {}
for i=1,nruns do
fn_init()
_norns.cpu_time_start_timer()
for j=1,nsteps do
fn_step()
end
local delta_ns = _norns.cpu_time_get_delta()
table.insert(times_ms, delta_ns / 1e6)
end
return times_ms
end
```

add cpu_time

---

matron/src/weaver.c

noticed `screen.peek` in lua was returning strings bigger than requested. turns out weaver was pushing the buffer using `lua_pushstring` which assumes null-termination; changed this to `lua_pushlstring` with explicit length.

set explicit length for peek results buffer

---

lua/core/osc.lua

Closes monome/norns-image#99
I'm often using OSC for modulating my Norns boxes from Ableton Live. It works very well but notoriously clogs up logs. This is from a few hours of runtime:
```
-rw-r-----   1 root adm             765M Nov  1 23:24 daemon.log
-rw-r-----   1 root adm             120M Nov  1 11:11 daemon.log.1
-rw-r-----   1 root adm              51K Oct 22 22:23 daemon.log.2.gz
-rw-r-----   1 root adm             201K Oct  8 13:18 daemon.log.3.gz
```
Sure, the logs get folded into gzip at some point but until that point literally gigabytes of space will be wasted. And the logs are harder to see during that time as when you are modulating a parameter with OSC, there can be 100+ log lines *per second* like:
```
Nov 01 23:23:49 shield ws-wrapper[516]: setting parameter /pw to …
```

Stop logging OSC

---

lua/core/screen.lua

The default screensaver time is 15 minutes. I like to manually turn the screensaver on sooner, which I can do from Maiden by calling:
```lua
>> screensaver:event()
```
To be able to do this, `screensaver` needs to be a global.

Add `Screen.sleep()` to manually invoke the screensaver

---

matron/src/clocks/clock_link.c

fix for start/stop syncing code mapping beat 0 to the wrong time, since link internals seem to have changed and no longer work with time value of 0.
for context and discussion see https://github.com/monome/norns/pull/1738

fix time for effective transport start/stop in clock_link

---

lua/lib/lfo.lua

[as reported at lines](https://llllllll.co/t/lfo-lib/60274/14), creating an LFO using the constructor methods should automatically populate the relevant settings when `:add_params` is invoked.
`mode` and `reset_target` were not being set as parameters correctly, as their values were not being matched to the table of options -- instead of doing a key lookup, i had accidentally passed the string values as the index. `period` was also not being handled correctly. i also needed to extend the group parameter count.
this PR corrects these issues!
test script:
```lua
_lfos = require 'lfo' -- assign the library to a general variable
engine.name = 'PolyPerc'
s = require 'sequins'
hz_vals = s{400,600,200,350}
sync_vals = s{1,1/3,1/2,1/6,2}
clock.run(iter)
screen_dirty = true
-- …
```

fix lfo constructor ahead of params

---

lua/core/clock.lua
lua/core/midi.lua
lua/core/state.lua
matron/src/device/device_midi.c
matron/src/device/device_midi.h
matron/src/weaver.c

addresses #1754 by means of a new clock parameter `clock_midi_in`. options are "all", "none", or a vport index. 
this seems to work, but needs:
- some cleanup (dbg prints)
- consideration of UI
- consideration of structure / efficiency (some quick and dirty loops and maybe not optimal FFI)

[WIP] Midi clock filter

---

lua/lib/fileselect.lua

closes #1758
there's a lot to dislike here—i added a half-second slowdown to _every_ time fileselect exits—this is because if tape playback is going to start, it needs a buffer of about that long from after being stopped.
that being said, i believe the reported issues are now fixed.

fix: more aggressively debounce tape playback

---

lua/core/grid.lua

from @catfact in https://llllllll.co/t/midigrid-use-launchpads-midi-grid-controllers-with-norns/42336/550:
> the examples in the comments in grid.lua incorrectly use the . field accessor in several places where i think they would need the : method accessor.
this PR swaps those field accessors for method accessors!

fix field accessors in grid example

---

lua/lib/hotswap.lua

fix for https://github.com/monome/norns/issues/1761
solution: copy hotswap.lua file from the crow lua lib to the norns lua lib
testing: after copying the code and restarting my norns, i tested from the maiden repl using the code from the crow [hotswap documentation](https://monome.org/docs/crow/reference/#hotswap):
```
sequins = require('sequins')
hotswap = require('hotswap')
-- the sequins is overwritten, but the playhead is preserved
hotswap.seq = sequins{1,2,3}
hotswap.seq() --> 1
hotswap.seq() --> 2
hotswap.seq = sequins{4,5,6,7}
hotswap.seq() --> 6
```

hotswap is missing from the norns/lib

---

matron/src/hardware/i2c.c
matron/src/main.c

refreshed norns PCB uses inf pots via an i2c ADC.
no config needed for mode switching.

support i2c adc inf pots for encoders

---

lua/core/encoders.lua
lua/core/norns.lua

since adc reports at fixed rate, time-based encoder acceleration doesn't work.
this new code make the ticks exponential which emulates the feeling of the encoders.
tuned with magic number.

accel for potentiometers

---

lua/core/menu.lua
lua/core/menu/params.lua
lua/core/params/binary.lua
lua/core/params/trigger.lua

while building docs for `binary`-style parameters, i came across a few API discontinuities, which this PR attempts to address.
- **E3 control**: as discussed in https://github.com/monome/norns/discussions/1752, E3 movement now only affects `"toggle"` behavior. it is ignored for `"momentary"` and `"trigger"`.
- **`params:set` now affects UI:**  previously, the `triggered` and `on` states for this param type did not update with `params:set`.
- **execute `"trigger"` without a value**: since triggers are _actions_, they can alternatively be executed with `params:set('example_trigger')` (this now matches the standard `trigger`-style parameter)
please  let me know if there's any additional questions or angles i missed! <3

improve binary-style params

---

lua/core/params/binary.lua
lua/core/paramset.lua

addresses #1784 
@dansimco , I pushed these changes to my local build two weeks ago and _totally_ spaced on PR'ing this to `main`. apologies for the oversight and thank you so so much for reporting the issue!

binary triggers: allow default of '1'

---

lua/core/paramset.lua

Hi y'all, this fixes an issue introduced in #1785 which prevents paramset:read() from setting non-binary param values on .pset load. I'm not particularly confident poking around core files, but it seems to do the trick in my testing!

fix for paramset:read() not setting values

---

lua/core/menu/sleep.lua

addresses [this TODO](https://github.com/monome/norns/blob/main/lua/core/menu/sleep.lua#L10) in service of closing https://github.com/monome/norns/issues/1436 (and just popping in a sox w/Lua API ticket [per this comment](https://github.com/monome/norns/issues/1436#issuecomment-936151213))

TAPE: stop recording on SLEEP

---

lua/core/paramset.lua

This PR addresses an issue that can cause "text" param values to be converted from strings to numbers when reading a pset file.
Note that the fix introduces the opposite behavior: if a text param was intentionally set with a number value, it will now be converted to a string upon pset read. That scenario seems like an edge case to me and is probably not how text params were intended to be used, but could still be seen as a breaking change.
Script to reproduce issue:
```lua
-- init param with a string value that can be converted to a number
params:add_text("text_1", "text_1", "1.1")
print("param type at init: " .. type(params:string("text_1"))) -- string
-- after saving and loading pset
params.action_read = function()
print("param type after pset read: " .. …
```

fix text param val converting to number

---

doc/modules/screen.html
lua/core/screen.lua
matron/src/hardware/screen.c

Provides  scripts with an alias from the old “04B_03__” system font that points to the new norns.ttf.

Alias 04B_03 font to norns.ttf

---

doc/modules/audio.html
lua/core/audio.lua

This PR documents the return values for `Audio.file_info`. These return values were validated against a known tape file:
```
> ch, samples, rate = audio.file_info("/home/we/dust/audio/tape/0001.wav")
> ch
2
> samples
72782080
> rate
48000
```
I wasn't sure whether I was supposed to regenerate the output html or not, so happy to remove that if it should be regenerated some other way.

Add return values for Audio.file_info

---

lua/core/crow.lua

While I playing around with the Norns wtape ii interface I noticed that `loop_start()` and `loop_end()` commands always failed:
```
> crow.ii.wtape[1].loop_start()
<ok>
crow:   repl:1: bad argument #1 to 'loop_start' (number expected, got nil)
crow:   stack traceback:
crow:   [C]: in field 'loop_start'
crow:   repl:1: in main chunk
crow:   runtime error.
```
This also happened for the wdel ii `clock()` command. After checking that Norns and crow were up-to-date, I tested the commands in druid and didn't have any issues. I also tested `crow.send("ii.wtape[1].loop_start()")` from Norns and didn't encounter the issue.
It turns out that Norns was sending the string `ii["wtape"][1]["loop_start"](nil)` to crow. I modified the `crowSub:__call` metamethod to check the number of varargs before …

support crow ii functions with zero arguments

---

lua/core/metro.lua

This change fixes (what seems to be) a bug in the metro module. The bug is demonstrated by the code below - install it on a norns as script.
In the script, K2 should initialise a metronome then start it from stage = 3. However, by tracking the output in `journalctl -f` we see it starts from stage = 1. The expected output can be seen by pressing K3.
```lua
-- Demo of metro bug
-- K2 = Test with a table
-- K3 = Test with args
function print_stage(stage)
print('stage = ' .. stage)
end
function key(n, z)
if n == 2 and z == 1 then
local m = metro.init(print_stage, 1, 6)
print('Starting metro at stage 3 using a table...')
m:start({stage = 3})
elseif n == 3 and z == 1 then
local m = metro.init(print_stage, 1, 6)
print('Starting metro at stage 3 using multiple args...')
m:start(1, 6, 3)
end
end …
```

Fix metro 'stage' bug

---

lua/core/menu/select.lua

This is bug fix and an enhancement.
1. It would be good to put test scripts in their own folder, out of the way of the main code, and to not have them show up in the SELECT menu. This change allows that by excluding a `test` folder from the SELECT menu.
2. The documentation at https://monome.org/docs/norns/reference/#folder-structure says anything in a `docs` folder is excluded from the SELECT menu. That's not true (if it's a Lua script). This change also ensures that exclusion happens.
This change is documented in `monome/docs` PR [#435](https://github.com/monome/docs/pull/435).

Exclude directories from SELECT menu

---

matron/src/hardware/platform.c
matron/src/hardware/platform.h

PR to expand `platform.c` to include other Pi variants including `PLATFORM_PI4`, `PLATFORM_CM4`, and `PLATFORM_CM4S`
Rationale: Addresses cases of norns shield users with a Compute Module 4 in a Waveshare carrier board where the user will get the display rotated by 180 because the platform is incorrectly interpreted.
Previously tested as working with CM4 in a Waveshare carrier board. Does not change original enum indexing, so it should not affect CM3 norns.

Add more Pi variant platforms

---

lua/core/startup.lua

This was being set in a mod so I didn't notice that it was missing from the standard globals. 🤦‍♀️ 
Without it, Norns was crashing as soon as a tty device was connected.

fix crash on tty device connection when no serial mod is enabled

---

matron/src/device/device_serial.c
matron/src/device/device_serial.h
matron/src/event_types.h
matron/src/events.c
matron/src/weaver.c
matron/src/weaver.h

Switch to using `lua_pushlstring` so that messages containing null characters can reach the Lua handler. This makes it possible to interpret the serial data as something other than ascii characters.
I also changed the serial event struct to embed a heap-allocated copy of the serial data. The serial read thread does not sleep other than waiting for IO. It's possible for it to read multiple times in a row before the event loop has a chance to process the messages if the serial device is sending a lot of data. This could lead to messages being overwritten in the buffer and effectively "dropped".
EDIT: Oops, just realized this affects sending messages also.

serial handlers can transmit and receive messages with embedded zeroes

---

lua/core/clock.lua
matron/src/clock.c
matron/src/clock.h
matron/src/clocks/clock_link.c
matron/src/clocks/clock_link.h
matron/src/weaver.c

this PR adds `_norns.clock_link_get_number_of_peers()` a new Lua function which will return the number of peers connected to this Norns over Ableton Link.
[related discussion on Lines:](https://llllllll.co/t/ableton-link-and-norns-question/39335/11?u=alanza)
~~this PR does *not* make a user-facing change to display the number of peers anywhere on norns, but it enables that change to be made solely in Lua. i'd happily help brainstorm or contribute that Lua change as well, if there's interest.~~

feat: add `clock.link.get_number_of_peers()`

---

matron/src/jack_client.c
matron/src/main.c

fixes #1830
Shows "audio system fail" when jack does not start.
Potential improvement might be "any key to shut down" --- currently shutdown requires remote login or white button. We don't want to shut down with a timer, to allow debugging.

issue screen error on audio system fail

---

matron/src/hardware/platform.c
matron/src/hardware/platform.h
matron/src/hardware/screen/ssd1322.c
matron/src/main.c

this probably impacts a very tiny number of norns users... possibly only one
* adds `platform_name()` function for obtaining a string representation of which platform was detected
* fixes "CM4S" detection, previously always reported as "CM4" due to substring matching
* chooses normal screen orientation for CM3, CM4, and CM4S devices (CM4 case is debatable)
* reports the platform name on startup along with platform enum number
warning: i haven't tested this on any other devices other than a unicorn og norns + cm4s

fix cm4s platform detection and screen

---

Dockerfile

This Dockerfile supports building the norns stack in an ARMv8 container with an OS environment that attempts to be as similar as possible to the norns disk image, from any host environment/architecture that can run Docker with the Docker BuildKit virtualization support (included in Docker Desktop, extra configuration required for Linux, [see here](https://docs.docker.com/build/building/multi-platform/#install-qemu-manually).)
Some additional details in the Dockerfile comments.
To run locally, the following two commands are sufficient to prepare the image and run the norns waf build process:
```zsh
% docker build -t norns-ci . 
% docker run -v $(PWD):/norns-build -t norns-ci 
```
The next step is to leverage this for CI using GitHub Actions. The simple strategy would be to have a single …

Add Dockerfile for CI

---

.github/workflows/compile.yml

This commit adds `.github/workflows/compile.yml` which uses the Dockerfile from #1838 to run a build of the norns system via GitHub Actions.
thanks very much to @Dewb for the help wrangling Docker!
currently the workflow effectively just gives a heads up or down about whether the changes compiled or not, and the docker image is hosted by my account on Docker Hub, while a GitHub Container Registry entry owned by Monome might make more sense. plenty of interesting future work possible from here, too, such as building new norns images, automatically running a test script, that sort of thing.

feat(ci): add compile step to use Dockerfile to build norns

---

.clang-format

_what?_
Fixed incorrect syntax in `.clang-format` configuration file on line 94.
_why?_
The `RawStringFormats` section had invalid syntax (`Delimiter: pb` instead of `Delimiters: [pb]`), preventing clang-format from running properly.
_therefore_
clang-format now works correctly with the `clang-format.sh` script for formatting C/C++ code in the project.

Fixes .clang-format syntax

---

lua/core/norns.lua
matron/src/hardware/battery.c
matron/src/hardware/i2c.c
matron/src/hardware/platform.c
matron/src/hardware/platform.h
matron/src/hardware/screen/ssd1322.c
matron/src/weaver.c

- adds `platform_{factory,shield}` functions to determine hw category
- changes screen flip logic to use `platform_factory`
- allows i2c and battery init if platform_factory == true
- allows i2c_hp if platform_factory == true
Overall this change appears bring a factory norns with cm4s up to functional parity with a cm3/cm3+ device. I would recommend testing on a cm3 based device before merging.

fix factory + cm4s headphone and battery
